# Generated by Django 3.1.5 on 2021-01-06 13:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_org_and_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.AddField(
            model_name='datasource',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('DHIS2', 'DHIS2'), ('IASO', 'Iaso'), ('FILES', 'Files')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('ACADEMIC', 'Academic'), ('GOVERNMENT', 'Government'), ('NGO', 'Non-governmental')], max_length=100),
        ),
        migrations.CreateModel(
            name='Dhis2Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('dhis2_id', models.CharField(max_length=100)),
                ('dhis2_code', models.CharField(max_length=100)),
                ('dhis2_indicator_type', models.CharField(choices=[('NUMBER_FACTOR_1', 'Number (Factor 1)'), ('PER_CENT', 'Per cent'), ('PER_HUNDRED_THOUSANDS', 'Per hundred thousand'), ('PER_TEN_THOUSAND', 'Per ten thousand'), ('PER_THOUSAND', 'Per thousand')], max_length=100)),
                ('annualized', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.organization')),
                ('source', models.ForeignKey(limit_choices_to={'source_type': 'DHIS2'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dhis2DataElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('dhis2_id', models.CharField(max_length=100)),
                ('dhis2_code', models.CharField(max_length=100)),
                ('dhis2_domain_type', models.CharField(choices=[('AGGREGATE', 'Aggregate'), ('TRACKER', 'Tracker')], max_length=100)),
                ('dhis2_value_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('LETTER', 'Letter'), ('PHONE_NUMBER', 'Phone number'), ('EMAIL', 'Email'), ('YES_NO', 'Yes/No'), ('YES_ONLY', 'Yes Only'), ('DATE', 'Date'), ('DATE_AND_TIME', 'Date & Time'), ('TIME', 'Time'), ('NUMBER', 'Number'), ('UNIT_INTERVAL', 'Unit interval'), ('PERCENTAGE', 'Percentage'), ('INTEGER', 'Integer'), ('POSITIVE_INTEGER', 'Positive Integer'), ('NEGATIVE_INTEGER', 'Negative Integer'), ('POSITIVE_OR_ZERO_INTEGER', 'Positive or Zero Integer'), ('TRACKER_ASSOCIATE', 'Tracker Associate'), ('USERNAME', 'Username'), ('COORDINATE', 'Coordinate'), ('ORGANISATION_UNIT', 'Organisation Unit'), ('AGE', 'Age'), ('URL', 'URL'), ('FILE', 'File'), ('IMAGE', 'Image')], max_length=100)),
                ('dhis2_aggregation_type', models.CharField(choices=[('SUM', 'Sum'), ('AVERAGE', 'Average')], max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.organization')),
                ('source', models.ForeignKey(limit_choices_to={'source_type': 'DHIS2'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
