# Generated by Django 3.2.6 on 2021-08-10 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
        ("connector_postgresql", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postgresqldatabasepermission",
            unique_together={("database", "team")},
        ),
    ]
