# Generated by Django 5.2.16 on 2026-10-01 09:03

import uuid

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceCopyJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "execute_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs with higher priority will be processed first.",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("args", models.JSONField()),
            ],
            options={
                "db_table": "workspace_copier_job",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceCopyRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Succeeded"),
                            ("SUCCESS_WITH_ERRORS", "Succeeded with errors"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_slug", models.CharField(max_length=255)),
                ("target_url", models.URLField(blank=True)),
                (
                    "target_organization_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("target_workspace_name", models.CharField(blank=True, max_length=255)),
                ("target_workspace_slug", models.CharField(blank=True, max_length=255)),
                ("resources", models.JSONField(default=list)),
                ("all_dataset_versions", models.BooleanField(default=False)),
                (
                    "source_token",
                    hexa.core.models.cryptography.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "target_token",
                    hexa.core.models.cryptography.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("logs", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("result_workspace_slug", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
