# Generated by Django 4.0.6 on 2022-09-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data_collections", "0002_collection_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionelement",
            name="object_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="collectionelement",
            name="object_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
