# Generated by Django 4.1.7 on 2023-07-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0004_alter_collectionelement_collection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionelement",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionelement",
            name="object_type",
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="CollectionElement",
        ),
    ]
