# Generated by Django 3.2.3 on 2021-05-27 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0003_abstract_index"),
        ("catalog", "0005_abstract_index"),
        ("core", "0005_abstract_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Index",
        ),
    ]
