# Generated by Django 4.0 on 2022-01-10 15:42

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_ltree"),
    ]

    operations = [CITextExtension()]
