# Generated by Django 4.0.6 on 2022-08-22 12:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_ci_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="name must be composed of letters only ",
                                regex="^[a-zA-Z]*$",
                            )
                        ],
                    ),
                ),
                (
                    "value",
                    hexa.core.models.cryptography.EncryptedTextField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="value must be alphanumeric ",
                                regex="^[a-zA-Z0-9]*$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
