# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_ci_text"),
    ]

    operations = []
    operations = []
