repos:
- repo: local
  hooks:
    - id: run-backend-pre-commit
      name: Run Backend Pre-Commit
      entry: ./backend/script/pre-commit.sh
      language: system
      types: [python]
    - id: run-frontend-pre-commit
      name: Run Frontend Pre-Commit
      entry: ./frontend/script/pre-commit.sh
      language: system
      types: [javascript, ts]