repos:
  - repo: https://github.com/pycqa/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - "-i"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        - id: isort
          name: isort (python)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
