repos:
- repo: local
  hooks:
    - id: run-frontend-pre-commit
      name: Run Frontend Pre-Commit
      entry: ./frontend/script/pre-commit.sh
      language: system
      files: ^frontend/
      types: [javascript, ts]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
      files: ^backend/
      types: [python]
    - id: ruff-format
      files: ^backend/
      types: [python]