FROM postgres:12.5

RUN apt-get update
RUN apt-get install -y postgis postgresql-12-postgis-3 --no-install-recommends

ENTRYPOINT ["docker-entrypoint.sh"]
STOPSIGNAL SIGINT
EXPOSE 5432
CMD ["postgres"]

