version: '3'

services:
  jupyterhub:
    build: jupyterhub
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_JUPYTER_CONTAINER: habari_jupyter
      DOCKER_NETWORK_NAME: habari_default
      HUB_IP: jupyterhub
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET_NAME:
    ports:
      - 8000:8000
    restart: on-failure

  jupyter:  # just used for building - the jupyterhub service will spawn jupyter containers on demand
    build: jupyter
    image: habari_jupyter
    command: echo