services:
  app: 
    user: "openhexa"
    group_add:
      - "openhexa"
    
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /code
          ignore:
            - ./backend/.venv
        - path: ./backend/requirements.txt
          action: rebuild 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./.env:/.env
      - ./backend:/backend
    environment:
      - DEBUG=
    develop:
      watch:
        - path: ./frontend/package-lock.json
          action: rebuild 
        - action: sync
          path: ./frontend
          target: /code
          ignore:
            - ./frontend/node_modules/
        