[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
  )/
  | node_modules
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.coverage.report]

exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
]

omit = [
    "*/__init__.py",
    "*/migrations/*",
    "*/tests/*",
    "config/*",
    "*/admin.py",
    "*/apps.py",
    "*/urls.py",
    "manage.py",
]
