hub:
  # see https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html?highlight=database#hub-db
  # (this is the "hub" database described in the README)
  db:
    type: postgres
auth:
  # see https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#github
  type: github
  admin:
    access: true
singleuser:
  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            cp -r /tmp/habari_sample_files/* /home/jovyan/;
            cp -r /tmp/ipython-startup/* /home/jovyan/.ipython/profile_default/startup;
            mkdir -p /home/jovyan/work;
  # see https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#optimizations
  # and https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-resources.html#set-user-memory-and-cpu-guarantees-limits
  cpu:
    limit: 4
    guarantee: 0.05
  memory:
    limit: 32G
    guarantee: 256M

scheduling:
  # see https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#optimizations
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 4
  userPods:
    nodeAffinity:
      matchNodePurpose: require

cull:
  # see https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-management.html?highlight=cull#culling-user-pods
  enabled: true
  timeout: 7200
  every: 300