# Generated by Django 3.2.3 on 2021-05-27 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_abstract_index"),
        ("pipelines", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinesindexpermission",
            name="pipeline_index",
        ),
        migrations.RemoveField(
            model_name="pipelinesindexpermission",
            name="team",
        ),
        migrations.DeleteModel(
            name="PipelinesIndex",
        ),
        migrations.DeleteModel(
            name="PipelinesIndexPermission",
        ),
    ]
