# Generated by Django 4.1.3 on 2023-03-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0016_remove_pipeline_entrypoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineversion",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="pipelines.pipeline",
            ),
        ),
    ]
