# Generated by Django 4.1.7 on 2023-03-21 14:53

from django.db import migrations, models


def forwards(apps, schema_editor):
    Pipeline = apps.get_model("pipelines", "Pipeline")
    PipelineRun = apps.get_model("pipelines", "PipelineRun")

    for pipeline in Pipeline.objects.all():
        pipeline.config = {}
        pipeline.save()

    for run in PipelineRun.objects.all():
        run.config = {}
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0017_alter_pipelineversion_pipeline"),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name="pipeline",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
