# Generated by Django 4.1.7 on 2023-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0018_alter_pipeline_config_alter_pipelinerun_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("name"),
                name="unique_pipeline_name_per_workspace",
            ),
        ),
    ]
