# Generated by Django 4.1.7 on 2023-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0021_pipeline_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipeline",
            name="unique_pipeline_name_per_workspace",
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("code"),
                name="unique_pipeline_code_per_workspace",
            ),
        ),
    ]
