# Generated by Django 4.1.7 on 2023-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0023_remove_pipelineversion_entrypoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pipeline",
            options={"verbose_name": "Pipeline"},
        ),
    ]
