# Generated by Django 4.1.7 on 2023-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0027_auto_20230719_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="timeout",
            field=models.IntegerField(null=True),
        ),
    ]
