# Generated by Django 4.1.7 on 2023-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0028_pipeline_timeout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="timeout",
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="timeout",
            field=models.IntegerField(null=True),
        ),
    ]
