# Generated by Django 4.1.7 on 2023-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0030_alter_pipelineversion_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="timeout",
            field=models.IntegerField(null=True),
        ),
    ]
