# Generated by Django 4.1.7 on 2023-12-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0032_pipeline_webhook_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="trigger_mode",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("manual", "Manual"),
                    ("webhook", "Webhook"),
                ],
                max_length=200,
            ),
        ),
    ]
