# Generated by Django 5.0 on 2024-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0035_alter_pipelineversion_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE pipelines_pipelineversion SET name = number",
        ),
        migrations.AlterField(
            model_name="pipelineversion",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
