# Generated by Django 5.0.2 on 2024-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0036_alter_pipelineversion_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelineversion",
            name="number",
        ),
    ]
