# Generated by Django 5.0.3 on 2024-06-14 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0042_pipelineversion_config"),
        ("pipelines", "0043_generate_webhook_token"),
    ]

    operations = []
