# Generated by Django 4.2.16 on 2024-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0052_pipelineversion_version_number_revert_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="log_level",
            field=models.IntegerField(
                choices=[
                    (0, "Debug"),
                    (1, "Info"),
                    (2, "Warning"),
                    (3, "Error"),
                    (4, "Critical"),
                ],
                default=1,
            ),
        ),
    ]
