# Generated by Django 4.2.17 on 2024-12-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0002_alter_pipelinetemplate_name"),
        ("pipelines", "0053_pipelinerun_log_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipelines",
                to="pipeline_templates.pipelinetemplate",
            ),
        ),
    ]
