# Generated by Django 5.2.4 on 2025-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0059_remove_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="auto_update_from_template",
            field=models.BooleanField(
                default=False,
                help_text="Automatically update this pipeline when its source template is updated",
            ),
        ),
    ]
