# Generated by Django 5.2.4 on 2025-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0060_pipeline_auto_update_from_template"),
        ("tags", "0001_metadata_rf_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="pipelines", to="tags.tag"
            ),
        ),
    ]
