# Generated by Django 5.2.4 on 2025-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0061_pipeline_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="functional_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("transformation", "Transformation"),
                    ("loading", "Loading"),
                    ("computation", "Computation"),
                ],
                help_text="Business purpose: 'extraction' for data ingestion, 'transformation' for processing, 'loading' for data output, 'computation' for analytics. Describes WHAT the pipeline does in data workflows. Optional field used for categorization.",
                max_length=200,
                null=True,
            ),
        ),
    ]
