# Generated by Django 5.2.4 on 2025-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0061_pipeline_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="functional_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("transformation", "Transformation"),
                    ("loading", "Loading"),
                    ("computation", "Computation"),
                ],
                help_text="The functional type of the pipeline",
                max_length=200,
                null=True,
            ),
        ),
    ]
