# Generated by Django 5.2.7 on 2025-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0062_pipeline_functional_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="state",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("queued", "Queued"),
                    ("terminating", "terminating"),
                    ("stopped", "Stopped"),
                    ("skipped", "Skipped"),
                ],
                max_length=200,
            ),
        ),
    ]
