# Generated by Django 5.2.9 on 2026-02-16 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_templates", "0012_pipelinetemplate_validated_at"),
        ("pipelines", "0063_alter_pipelinerun_state"),
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
        ("workspaces", "0057_fix_readonly_role_grants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["name"], name="idx_pipeline_name"),
        ),
    ]
