# Generated by Django 5.2.9 on 2026-02-16 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0012_pipelinetemplate_validated_at"),
        ("pipelines", "0064_pipelinerun_resource_limits"),
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
        ("workspaces", "0057_fix_readonly_role_grants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["name"], name="idx_pipeline_name"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["pipeline", "-execution_date"],
                name="pipelines_p_pipelin_c58fed_idx",
            ),
        ),
    ]
