# Generated by Django 5.2.16 on 2026-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0067_pipeline_scheduled_pipeline_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineversion",
            name="dag",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
