# Generated by Django 3.1.6 on 2021-02-11 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("dhis2connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhis2dataelement",
            name="dhis2_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2dataelement",
            name="dhis2_external_access",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2dataelement",
            name="dhis2_favorite",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2dataelement",
            name="dhis2_last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="dhis2_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="dhis2_external_access",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="dhis2_favorite",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="dhis2_last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Dhis2IndicatorType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("dhis2_code", models.CharField(blank=True, max_length=100)),
                ("dhis2_name", models.CharField(max_length=200)),
                ("dhis2_short_name", models.CharField(blank=True, max_length=100)),
                ("dhis2_description", models.TextField(blank=True)),
                ("dhis2_external_access", models.BooleanField()),
                ("dhis2_favorite", models.BooleanField()),
                ("dhis2_created", models.DateTimeField()),
                ("dhis2_last_updated", models.DateTimeField()),
                ("dhis2_number", models.BooleanField()),
                ("dhis2_factor", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.area",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.datasource",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["dhis2_name"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="dhis2indicator",
            name="dhis2_indicator_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dhis2connector.dhis2indicatortype",
            ),
        ),
    ]
