# Generated by Django 3.1.6 on 2021-02-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dhis2connector", "0002_dhis2_indicator_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhis2indicatortype",
            name="dhis2_code",
        ),
    ]
