# Generated by Django 3.1.6 on 2021-02-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_area_themes_many2many"),
        ("dhis2connector", "0004_dhis2_preferred_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhis2dataelement",
            name="area",
        ),
        migrations.RemoveField(
            model_name="dhis2dataelement",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="dhis2indicator",
            name="area",
        ),
        migrations.RemoveField(
            model_name="dhis2indicator",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="dhis2indicatortype",
            name="area",
        ),
        migrations.RemoveField(
            model_name="dhis2indicatortype",
            name="theme",
        ),
        migrations.AddField(
            model_name="dhis2dataelement",
            name="areas",
            field=models.ManyToManyField(blank=True, to="catalog.Area"),
        ),
        migrations.AddField(
            model_name="dhis2dataelement",
            name="themes",
            field=models.ManyToManyField(blank=True, to="catalog.Theme"),
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="areas",
            field=models.ManyToManyField(blank=True, to="catalog.Area"),
        ),
        migrations.AddField(
            model_name="dhis2indicator",
            name="themes",
            field=models.ManyToManyField(blank=True, to="catalog.Theme"),
        ),
        migrations.AddField(
            model_name="dhis2indicatortype",
            name="areas",
            field=models.ManyToManyField(blank=True, to="catalog.Area"),
        ),
        migrations.AddField(
            model_name="dhis2indicatortype",
            name="themes",
            field=models.ManyToManyField(blank=True, to="catalog.Theme"),
        ),
        migrations.AlterField(
            model_name="dhis2dataelement",
            name="dhis2_aggregation_type",
            field=models.CharField(
                choices=[
                    ("AVERAGE", "Average"),
                    ("AVERAGE_SUM_ORG_UNIT ", "Average sum for org unit"),
                    ("COUNT", "Count"),
                    ("CUSTOM", "Custom"),
                    ("DEFAULT", "Default"),
                    ("LAST", "Last"),
                    ("LAST_AVERAGE_ORG_UNIT", "Last average for org unit"),
                    ("MAX", "Max"),
                    ("MIN", "Min"),
                    ("NONE", "None"),
                    ("STDDEV", "Standard Deviation"),
                    ("SUM", "Sum"),
                    ("VARIANCE", "Variance"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dhis2dataelement",
            name="dhis2_value_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("LONG_TEXT", "Long text"),
                    ("LETTER", "Letter"),
                    ("PHONE_NUMBER", "Phone number"),
                    ("EMAIL", "Email"),
                    ("YES_NO", "Yes/No"),
                    ("YES_ONLY", "Yes Only"),
                    ("DATE", "Date"),
                    ("DATE_AND_TIME", "Date & Time"),
                    ("TIME", "Time"),
                    ("NUMBER", "Number"),
                    ("UNIT_INTERVAL", "Unit interval"),
                    ("PERCENTAGE", "Percentage"),
                    ("INTEGER", "Integer"),
                    ("INTEGER_POSITIVE", "Positive Integer"),
                    ("INTEGER_NEGATIVE", "Negative Integer"),
                    ("INTEGER_ZERO_OR_POSITIVE", "Positive or Zero Integer"),
                    ("TRACKER_ASSOCIATE", "Tracker Associate"),
                    ("USERNAME", "Username"),
                    ("COORDINATE", "Coordinate"),
                    ("ORGANISATION_UNIT", "Organisation Unit"),
                    ("AGE", "Age"),
                    ("URL", "URL"),
                    ("FILE", "File"),
                    ("IMAGE", "Image"),
                ],
                max_length=100,
            ),
        ),
    ]
