# Generated by Django 3.2.7 on 2021-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("url", models.TextField()),
                ("method", models.IntegerField(choices=[(1, "Get"), (2, "Post")])),
                ("request_time", models.DateTimeField()),
                ("response_status", models.IntegerField()),
                ("response_content_length", models.IntegerField()),
                ("response_time", models.DateTimeField()),
                ("user_agent", models.TextField()),
                ("user_lang", models.TextField()),
                ("referer", models.TextField()),
            ],
        ),
    ]
