# Generated by Django 5.0 on 2024-01-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_add_query_string"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Request",
        ),
    ]
