# Generated by Django 4.2.17 on 2025-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0003_alter_pipelinetemplate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinetemplate",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
