# Generated by Django 5.2.4 on 2025-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0008_remove_feature_flag"),
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplate",
            name="functional_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("transformation", "Transformation"),
                    ("loading", "Loading"),
                    ("computation", "Computation"),
                ],
                help_text="Describes WHAT the template does in data workflows. Optional field used for categorization.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pipelinetemplate",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="pipeline_templates", to="tags.tag"
            ),
        ),
    ]
