# Generated by Django 5.2.7 on 2025-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0009_add_tags_and_functional_type"),
        ("pipelines", "0062_pipeline_functional_type"),
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
        ("workspaces", "0051_workspace_configuration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipelinetemplate",
            index=models.Index(fields=["name"], name="idx_template_name"),
        ),
        migrations.AddIndex(
            model_name="pipelinetemplate",
            index=models.Index(
                fields=["functional_type"], name="idx_template_func_type"
            ),
        ),
    ]
