# Generated by Django 5.2.7 on 2025-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0010_add_search_indexes"),
        ("pipelines", "0062_pipeline_functional_type"),
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
        ("workspaces", "0051_workspace_configuration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipelinetemplate",
            index=models.Index(
                fields=["workspace", "functional_type"],
                name="idx_template_ws_func_type",
            ),
        ),
    ]
