# Generated by Django 5.2.7 on 2025-10-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0011_add_combined_workspace_functype_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplate",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text="Publisher of the template (e.g., 'Bluesquare', 'Community').",
                max_length=200,
                null=True,
            ),
        ),
    ]
