# Generated by Django 5.2.7 on 2025-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0011_add_combined_workspace_functype_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplate",
            name="validated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the template was validated as official. If set, shows organization name/logo; if null, shows 'Community'.",
                null=True,
            ),
        ),
    ]
