# Generated by Django 5.2.7 on 2025-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0011_add_combined_workspace_functype_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplate",
            name="icon_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the icon/logo image for this template (for official templates).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pipelinetemplate",
            name="is_official",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this template is officially vetted by Bluesquare or the organization.",
            ),
        ),
    ]
