# Generated by Django 5.2.7 on 2025-10-15 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0012_add_official_status_and_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinetemplate",
            name="icon_url",
        ),
        migrations.RemoveField(
            model_name="pipelinetemplate",
            name="is_official",
        ),
    ]
