# Generated by Django 5.2.13 on 2026-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0013_version_name_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinetemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
