# Generated by Django 3.1.5 on 2021-01-29 03:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("habari_auth", "0001_custom_user_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.RunSQL(
            "ALTER table django_admin_log ALTER COLUMN user_id type char using user_id::char;"
            + "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE uuid USING user_id::uuid;",
            "ALTER table django_admin_log ALTER COLUMN user_id type char using user_id::char;"
            + "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE integer USING user_id::integer;",
        ),
    ]
