# Generated by Django 3.1.5 on 2021-02-04 09:38

from django.db import migrations, models
import habari.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("habari_auth", "0001_custom_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", habari.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                help_text="For display purposes only.",
                max_length=150,
                verbose_name="username",
            ),
        ),
    ]
