# Generated by Django 3.2.7 on 2021-11-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaldashboard",
            name="name",
        ),
    ]
