# Generated by Django 3.2.7 on 2021-11-19 09:21

from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_remove_externaldashboard_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldashboard",
            name="credentials",
            field=hexa.core.models.cryptography.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="externaldashboard",
            name="picture",
            field=models.FileField(upload_to="external_dashboard"),
        ),
    ]
