# Generated by Django 3.2.7 on 2021-11-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_auto_20211119_0921"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={
                "ordering": ("label",),
                "verbose_name": "Dashboard index",
                "verbose_name_plural": "Dashboard indexes",
            },
        ),
    ]
