# Generated by Django 4.0.4 on 2022-06-19 18:24

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_data_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="WHOBoundary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("administrative_level", models.IntegerField()),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="countries.country",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="childrens",
                        to="countries.whoboundary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
