# Generated by Django 3.1.6 on 2021-02-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_stats"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stat",
        ),
    ]
