# Generated by Django 5.0.8 on 2024-10-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadataattribute",
            name="value",
            field=models.JSONField(default={}),
        ),
    ]
