# Generated by Django 4.2.16 on 2024-09-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="metadataattribute",
            name="unique_key_per_data_object",
        ),
        migrations.RemoveField(
            model_name="metadataattribute",
            name="content_type",
        ),
        migrations.AddField(
            model_name="metadataattribute",
            name="object_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadataattribute",
            constraint=models.UniqueConstraint(
                fields=("object_content_type", "object_id", "key"),
                name="unique_key_per_data_object",
            ),
        ),
    ]
