# Generated by Django 4.2.16 on 2024-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metadata",
            "0002_remove_metadataattribute_unique_key_per_data_object_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metadataattribute",
            index=models.Index(
                fields=["object_content_type", "object_id", "key"],
                name="index_object_key",
            ),
        ),
    ]
