# Generated by Django 4.2.17 on 2025-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0003_alter_metadataattribute_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataattribute",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
