pipelines_parameters_with_scalars = [
    {
        "code": "param1",
        "name": "Param 1",
        "type": "str",
        "help": "Param 1's Help",
        "default": "default value",
        "multiple": True,
        "required": True,
        "choices": ["Choice 1", "Choice 2"],
    },
    {
        "code": "param2",
        "name": "Param 2",
        "type": "int",
        "help": "Param 2's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param3",
        "name": "Param 3",
        "type": "float",
        "help": "Param 3's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param4",
        "name": "Param 4",
        "type": "bool",
        "help": "Param 4's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
]

pipelines_parameters_with_connections = [
    {
        "code": "param1",
        "name": "Param 1",
        "type": "dataset",
        "help": "Param 1's Help",
        "default": "default value",
        "multiple": False,
        "required": False,
        "choices": [],
    },
    {
        "code": "param2",
        "name": "Param 2",
        "type": "dhis2",
        "help": "Param 2's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param3",
        "name": "Param 3",
        "type": "postgresql",
        "help": "Param 3's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param4",
        "name": "Param 4",
        "type": "iaso",
        "help": "Param 4's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param5",
        "name": "Param 5",
        "type": "s3",
        "help": "Param 5's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param6",
        "name": "Param 6",
        "type": "gcs",
        "help": "Param 6's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param7",
        "name": "Param 7",
        "type": "custom",
        "help": "Param 7's Help",
        "default": "default value",
        "multiple": False,
        "required": True,
        "choices": [],
    },
]

pipelines_parameters_unvalid = [
    {
        "code": "param1",
        "name": "Param 1",
        "type": "dhis3",
        "help": "Param 1's Help",
        "default": "default value",
        "multiple": False,
        "required": False,
        "choices": [],
    }
]

pipelines_example_parameters = [
    {
        "code": "param1",
        "name": "Param 1",
        "type": "str",
        "help": "Param 1's Help",
        "default": None,
        "multiple": False,
        "required": True,
        "choices": [],
    },
    {
        "code": "param2",
        "name": "Param 2",
        "type": "str",
        "help": "Param 2's Help",
        "default": None,
        "multiple": False,
        "required": True,
        "choices": [],
    },
]
