# Generated by Django 5.0.8 on 2024-10-17 20:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAccessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("workspace_user", "Workspace User"),
                            ("token", "Token"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("flagged", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_access_rules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("workspace", "path")},
            },
        ),
    ]
