# Generated by Django 5.2.14 on 2026-07-08 13:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0060_grant_create_on_public_to_rw_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("content", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_queries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["workspace", "-updated_at"], name="data_studio_ws_updated_idx"
            ),
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                            ("DENIED", "Denied"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=5, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(null=True)),
                ("row_count", models.PositiveIntegerField(null=True)),
                ("truncated", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        choices=[("OTHER", "Other"), ("DATA_STUDIO", "Data Studio")],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("target", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="data_studio_workspa_a122ff_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="data_studio_user_id_54814c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_studio_status_eb07be_idx"
                    ),
                    models.Index(
                        fields=["origin"], name="data_studio_origin_123a01_idx"
                    ),
                    models.Index(
                        fields=["target"], name="data_studio_target_ce8817_idx"
                    ),
                ],
            },
        ),
    ]
