# Generated by Django 5.2.15 on 2026-07-29 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_studio", "0002_querylog"),
        ("workspaces", "0061_grant_select_on_covid_data_to_ro_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savedquery",
            name="data_studio_ws_updated_idx",
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["workspace", "-updated_at", "id"],
                name="data_studio_ws_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["workspace", "name", "id"], name="data_studio_ws_name_idx"
            ),
        ),
    ]
