# Generated by Django 5.2.15 on 2026-07-30 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0002_querylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedquery",
            options={
                "ordering": ["-updated_at"],
                "verbose_name_plural": "saved queries",
            },
        ),
    ]
