# Generated by Django 5.2.15 on 2026-07-31 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0003_alter_savedquery_options"),
        ("data_studio", "0003_remove_savedquery_data_studio_ws_updated_idx_and_more"),
    ]

    operations = []
