# Generated by Django 5.2.15 on 2026-08-04 10:51

from django.conf import settings
from django.db import migrations, models


def share_pre_existing_queries(apps, schema_editor):
    """Keep already-saved queries visible to their workspace.

    They were all created under the previous "shared with the whole workspace"
    semantics, so defaulting them to PRIVATE would silently hide colleagues' work.
    New queries start private instead - hence the field default.
    """
    SavedQuery = apps.get_model("data_studio", "SavedQuery")
    SavedQuery.objects.update(visibility="WORKSPACE")


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0004_merge_20260731_2053"),
        ("workspaces", "0062_merge_20260804_0809"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savedquery",
            name="visibility",
            field=models.CharField(
                choices=[("PRIVATE", "Private"), ("WORKSPACE", "Workspace")],
                default="PRIVATE",
                max_length=20,
            ),
        ),
        migrations.RunPython(share_pre_existing_queries, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["workspace", "created_by", "-updated_at", "id"],
                name="data_studio_ws_author_idx",
            ),
        ),
    ]
