# Generated by Django 5.2.15 on 2026-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0004_merge_20260731_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="origin",
            field=models.CharField(
                choices=[
                    ("OTHER", "Other"),
                    ("DATA_STUDIO", "Data Studio"),
                    ("DATA_STUDIO_EXPORT", "Data Studio Export"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("DENIED", "Denied"),
                    ("REJECTED", "Rejected"),
                    ("STREAMING", "Streaming"),
                ],
                max_length=10,
            ),
        ),
    ]
