# Generated by Django 5.2.15 on 2026-08-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0005_savedquery_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="saved_query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="query_logs",
                to="data_studio.savedquery",
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="origin",
            field=models.CharField(
                choices=[
                    ("OTHER", "Other"),
                    ("DATA_STUDIO", "Data Studio"),
                    ("WEBAPP", "Webapp"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
