# Generated by Django 5.2.15 on 2026-08-17 08:54

from django.conf import settings
from django.db import migrations, models

import hexa.data_studio.models


def delete_orphaned_private_queries(apps, schema_editor):
    """Drop private queries left behind by users deleted before this migration.

    `created_by` used to be SET_NULL, so those queries survived their author as rows
    no workspace or organization role gives access to: unreachable for everyone but a
    superuser, and kept forever for nobody.
    """
    SavedQuery = apps.get_model("data_studio", "SavedQuery")
    SavedQuery.objects.filter(visibility="PRIVATE", created_by__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0005_savedquery_visibility_and_more"),
        ("workspaces", "0062_merge_20260804_0809"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedquery",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=hexa.data_studio.models.saved_queries_on_author_deleted,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # The cleanup has to come first: the constraint is validated against the rows
        # already in the table.
        migrations.RunPython(
            delete_orphaned_private_queries, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="savedquery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("created_by__isnull", False),
                    models.Q(("visibility", "PRIVATE"), _negated=True),
                    _connector="OR",
                ),
                name="data_studio_private_query_has_author",
            ),
        ),
    ]
