# Generated by Django 5.2.15 on 2026-08-20 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0007_alter_querylog_origin_alter_querylog_status"),
        ("data_studio", "0007_querylog_saved_query"),
    ]

    operations = []
