# Generated by Django 5.2.15 on 2026-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0008_merge_20260820_0706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="origin",
            field=models.CharField(
                choices=[
                    ("OTHER", "Other"),
                    ("DATA_STUDIO", "Data Studio"),
                    ("DATA_STUDIO_EXPORT", "Data Studio Export"),
                    ("WEBAPP", "Webapp"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
