# Generated by Django 5.2.16 on 2026-09-11 10:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0009_alter_querylog_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="parameters",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
