# Generated by Django 5.2.16 on 2026-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_studio", "0010_querylog_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedquery",
            name="parameters",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
