# Generated by Django 3.2.6 on 2021-08-10 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
        (
            "connector_postgresql",
            "0002_alter_postgresqldatabasepermission_unique_together",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostgresqlDatabase",
            new_name="Database",
        ),
        migrations.RenameModel(
            old_name="PostgresqlDatabasePermission",
            new_name="DatabasePermission",
        ),
    ]
