# Generated by Django 3.2.6 on 2021-08-23 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("connector_postgresql", "0003_rename_to_plain_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_postgresql.database",
                    ),
                ),
            ],
            options={
                "verbose_name": "PostgreSQL table",
                "ordering": ["name"],
            },
        ),
    ]
