# Generated by Django 3.2.7 on 2021-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_postgresql", "0006_postgres_base_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="auto_sync",
            field=models.BooleanField(default=True),
        ),
    ]
