# Generated by Django 4.0.4 on 2022-04-13 05:08

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_user_management_to_identity_1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_postgresql", "0008_alter_database_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="databasepermission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="databasepermission",
            name="mode",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="EDITOR",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="databasepermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="databasepermission",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="databasepermission",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("user"),
                django.db.models.expressions.F("team"),
                django.db.models.expressions.F("database"),
                name="databasee_user_team",
            ),
        ),
    ]
