from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from hexa.assistant.agents.base import BaseAgent
from hexa.assistant.agents.create_pipeline_agent import CreatePipelineAgent
from hexa.assistant.agents.edit_pipeline_agent import EditPipelineAgent
from hexa.assistant.instructions import InstructionSet
from hexa.assistant.model_builder import BuiltModel

if TYPE_CHECKING:
    from hexa.assistant.models import Conversation

_AGENT_REGISTRY: dict[InstructionSet, type[BaseAgent]] = {
    InstructionSet.CREATE_PIPELINE: CreatePipelineAgent,
    InstructionSet.EDIT_PIPELINE: EditPipelineAgent,
    InstructionSet.GENERAL: BaseAgent,
}


def create_agent(
    conversation: Conversation, built_model: BuiltModel | None = None
) -> BaseAgent:
    agent_class = _AGENT_REGISTRY.get(
        InstructionSet(conversation.instruction_set), BaseAgent
    )
    return agent_class(conversation, built_model)


def all_agent_tool_names() -> set[str]:
    """Names of every tool any agent can call — i.e. every tool name that can
    surface in a conversation, and therefore in the frontend. This is the union
    across agents, so it includes agent-only tools like ``propose_pipeline_version``
    that are not in ``hexa.mcp.tools``. This is the source of truth for the
    generated ``AssistantToolName`` GraphQL enum the frontend keys off (see
    ``AGENT_TOOLS_SCHEMA_PATH`` and ``dump_agent_tools``)."""
    return {func.__name__ for cls in _AGENT_REGISTRY.values() for func in cls.tools}


# GraphQL SDL mirror of ``all_agent_tool_names()``, regenerated by the
# ``dump_agent_tools`` management command and guarded by a test so it can never
# silently drift. This file is *not* loaded into the runtime schema; it exists
# only so GraphQL codegen emits an ``AssistantToolName`` enum the frontend keys
# off, deriving tool identities from the agent registry with no hand-kept list.
AGENT_TOOLS_SCHEMA_PATH = (
    Path(__file__).resolve().parent.parent
    / "graphql"
    / "assistant_tools.generated.graphql"
)

_AGENT_TOOLS_SCHEMA_HEADER = (
    "# GENERATED by `manage dump_agent_tools` — do not edit by hand.\n"
    "# Mirrors the union of every agent's tools (hexa.assistant.agents.all_agent_tool_names).\n"
    "# This file feeds GraphQL codegen only; it is not loaded into the runtime schema,\n"
    "# so it adds no field/type to the live API — it exists purely to type the frontend.\n"
)


def render_agent_tools_schema() -> str:
    members = "\n".join(f"  {name}" for name in sorted(all_agent_tool_names()))
    return f"{_AGENT_TOOLS_SCHEMA_HEADER}enum AssistantToolName {{\n{members}\n}}\n"
