# Generated by Django 4.1.3 on 2022-12-22 10:59

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="country",
        ),
        migrations.AddField(
            model_name="workspace",
            name="countries",
            field=django_countries.fields.CountryField(
                blank=True, max_length=746, multiple=True
            ),
        ),
    ]
