# Generated by Django 4.1.3 on 2023-01-06 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_remove_workspace_country_workspace_countries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="members",
        ),
    ]
