# Generated by Django 4.1.3 on 2023-01-12 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0004_remove_workspace_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                through="workspaces.WorkspaceMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
