# Generated by Django 4.1.3 on 2023-01-17 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_rename_slug_workspaceconnection__slug"),
        ("workspaces", "0005_workspace_members_alter_workspace_created_by"),
    ]

    operations = []
