# Generated by Django 4.1.3 on 2023-01-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0006_merge_20230117_1448"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspaceconnection",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="workspaceconnectionfield",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterField(
            model_name="workspaceconnection",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="workspaces.workspace",
            ),
        ),
    ]
