# Generated by Django 4.1.3 on 2023-02-08 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0009_alter_workspace_slug"),
        ("workspaces", "0013_alter_connectionfield_options"),
    ]

    operations = []
