# Generated by Django 4.1.3 on 2023-02-10 08:50

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0015_alter_connectionfield_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="bucket_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="slug",
            field=models.CharField(
                editable=False,
                max_length=63,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
