# Generated by Django 4.1.3 on 2023-02-24 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0016_workspace_bucket_name_alter_workspace_slug"),
        ("workspaces", "0017_alter_workspace_db_name_alter_workspace_db_password"),
    ]

    operations = []
