# Generated by Django 4.1.3 on 2023-03-07 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0018_merge_20230224_1647"),
        ("workspaces", "0019_workspace_membership_hash_unique"),
    ]

    operations = []
