# Generated by Django 4.1.3 on 2023-03-07 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0020_merge_20230307_1200"),
        ("workspaces", "0020_merge_20230307_1248"),
    ]

    operations = []
