# Generated by Django 4.1.3 on 2023-03-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0021_merge_20230307_1321"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                models.F("workspace"),
                models.F("user"),
                name="workspace_membership_unique_workspace_user",
            ),
        ),
    ]
