# Generated by Django 4.1.7 on 2023-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspaces",
            "0022_workspacemembership_workspace_membership_unique_workspace_user",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
