# Generated by Django 4.1.7 on 2023-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("workspaces", "0026_workspacemembership_token"),
        ("workspaces", "0027_remove_workspacemembership_token_and_more"),
        ("workspaces", "0028_alter_workspacemembership_access_token"),
    ]

    dependencies = [
        ("workspaces", "0025_connection_connection_unique_workspace_connection_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="notebooks_server_hash",
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="access_token",
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
