# Generated by Django 4.1.7 on 2023-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0032_workspaceinvitation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectionfield",
            options={"ordering": ("created_at",)},
        ),
    ]
