# Generated by Django 4.2.6 on 2023-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0039_alter_workspaceinvitation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="docker_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
