# Generated by Django 4.2.6 on 2023-11-22 13:14

from django.db import migrations


def update_s3_connections_access_key_secret(apps, schema_editor):
    Connection = apps.get_model("workspaces", "Connection")
    ConnectionField = apps.get_model("workspaces", "ConnectionField")

    s3_connections = Connection.objects.filter(connection_type="S3")
    fields = []
    for conn in s3_connections:
        access_key_secret_field = conn.fields.filter(code="access_key_secret").first()
        access_key_secret_field.secret = True
        fields.append(access_key_secret_field)

    ConnectionField.objects.bulk_update(fields, ["secret"])


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0039_alter_workspaceinvitation_email"),
    ]

    operations = [
        migrations.RunPython(
            update_s3_connections_access_key_secret,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
