# Generated by Django 5.0 on 2024-02-06 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0043_alter_workspaceinvitation_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workspaceinvitation",
            name="workspace_invitation_unique_workspace_email",
        ),
    ]
