# Generated by Django 5.2 on 2025-05-12 19:09

from django.db import migrations

from hexa.workspaces.models import WorkspaceInvitationStatus

"""
To align with the new behavior of directly adding existing users to the workspace
instead of inviting them, we accept all pending workspace invitations.
"""


def accept_pending_invitations(apps, schema_editor):
    User = apps.get_model("user_management", "User")
    WorkspaceInvitation = apps.get_model("workspaces", "WorkspaceInvitation")
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")

    invitations = WorkspaceInvitation.objects.filter(
        status=WorkspaceInvitationStatus.PENDING
    )

    print(f"Found {invitations.count()} pending invitations")
    accepted_invitations = 0

    for invitation in invitations:
        existing_user = User.objects.filter(email=invitation.email).first()
        if not existing_user:
            continue

        is_already_a_member = WorkspaceMembership.objects.filter(
            user=existing_user, workspace=invitation.workspace
        ).exists()
        if is_already_a_member:
            continue

        WorkspaceMembership.objects.create(
            workspace=invitation.workspace, user=existing_user, role=invitation.role
        )
        invitation.status = WorkspaceInvitationStatus.ACCEPTED
        invitation.save()
        accepted_invitations += 1

    print(f"Done. Accepted {accepted_invitations} pending invitations.")


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0046_remove_create_feature_flag"),
    ]

    operations = [
        migrations.RunPython(
            accept_pending_invitations, reverse_code=migrations.RunPython.noop
        )
    ]
