# Generated by Django 5.2.1 on 2025-06-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_management",
            "0022_organizationmembership_organization_members_and_more",
        ),
        ("workspaces", "0047_accept_pending_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="user_management.organization",
            ),
        ),
    ]
