# Generated by Django 5.2.1 on 2025-08-18 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0049_migrate_workspaces_to_bluesquare_organization"),
        ("workspaces", "0049_organizationworkspaceinvitation"),
    ]

    operations = []
