# Generated by Django 5.2.4 on 2025-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0050_merge_20250818_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom configuration properties for the workspace as key-value pairs",
            ),
        ),
    ]
