# Generated by Django 5.2.7 on 2025-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0051_workspace_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
