# Generated by Django 5.2.7 on 2025-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0052_workspace_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinvitation",
            name="organization_role",
            field=models.CharField(
                blank=True,
                choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")],
                help_text="Optional organization role to assign when user accepts invitation",
                max_length=50,
                null=True,
            ),
        ),
    ]
