# Generated by Django 5.2.15 on 2026-08-04 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0061_grant_select_on_covid_data_to_ro_role"),
        ("workspaces", "0061_workspace_organization_required"),
    ]

    operations = []
