# Generated by Django 5.2.15 on 2026-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_remove_tag_tag_name_not_empty_alter_tag_name"),
        ("workspaces", "0062_merge_20260804_0809"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="workspaces", to="tags.tag"
            ),
        ),
    ]
