# Generated by Django 5.2.15 on 2026-09-09 11:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0064_backfill_bucket_cors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceTokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_fingerprint", models.CharField(max_length=32)),
                ("token_type", models.CharField(max_length=20)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("IN_SCOPE", "In scope"),
                            ("CROSS_REACHABLE", "Reachable from the token's workspace"),
                            ("OUT_OF_SCOPE", "Out of scope"),
                        ],
                        max_length=20,
                    ),
                ),
                ("root_fields", models.JSONField(default=list)),
                ("foreign_workspaces", models.JSONField(default=dict)),
                ("client", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at", "verdict"],
                        name="workspaces__created_1d2e73_idx",
                    ),
                    models.Index(
                        fields=["token_fingerprint"],
                        name="workspaces__token_f_8bd617_idx",
                    ),
                ],
            },
        ),
    ]
