# Generated by Django 5.0.2 on 2024-02-08 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_attach_to_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
