mock_data_elements_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 2,
        "pageSize": 100,
    },
    "dataElements": [
        {
            "code": "EMM_TYY_HXX",
            "lastUpdated": "2015-10-14T13:36:36.040",
            "id": "m3TSrzUIVlm",
            "href": "https://play.dhis2.org/demo/api/dataElements/m3TSrzUIVlm",
            "created": "2014-11-29T20:30:04.338",
            "name": "WHOMCH Uterotonics given",
            "shortName": "Uterotonics given",
            "aggregationType": "SUM",
            "domainType": "TRACKER",
            "displayName": "WHOMCH Uterotonics given",
            "publicAccess": "rw------",
            "description": "If person was treated with uterotonics",
            "displayShortName": "Uterotonics given",
            "externalAccess": False,
            "periodOffset": 0,
            "valueType": "BOOLEAN",
            "formName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "displayDescription": "If person was treated with uterotonics",
            "dimensionItem": "m3XQrgadVK9",
            "sharing": {
                "owner": "xE7jOejl9FI",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "zeroIsSignificant": False,
            "favorite": False,
            "optionSetValue": False,
            "dimensionItemType": "DATA_ELEMENT",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "categoryCombo": {"id": "bjDvmb4bfuf"},
            "createdBy": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "user": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "favorites": [],
            "dataSetElements": [],
            "translations": [],
            "userGroupAccesses": [],
            "dataElementGroups": [],
            "attributeValues": [],
            "userAccesses": [],
            "legendSets": [],
            "aggregationLevels": [],
        },
        {
            "code": "EMM_TYY_HX2",
            "lastUpdated": "2015-10-14T13:36:36.040",
            "id": "m3TSrzUIVl3",
            "href": "https://play.dhis2.org/demo/api/dataElements/m3TSrzUIVl3",
            "created": "2014-11-29T20:30:04.338",
            "name": "WHOMCH Uterotonics given",
            "shortName": "Uterotonics given",
            "aggregationType": "SUM",
            "domainType": "TRACKER",
            "displayName": "WHOMCH Uterotonics given",
            "publicAccess": "rw------",
            "description": "If person was treated with uterotonics",
            "displayShortName": "Uterotonics given",
            "externalAccess": False,
            "periodOffset": 0,
            "valueType": "BOOLEAN",
            "formName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "displayDescription": "If person was treated with uterotonics",
            "dimensionItem": "m3XQrgadVK9",
            "sharing": {
                "owner": "xE7jOejl9FI",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "zeroIsSignificant": False,
            "favorite": False,
            "optionSetValue": False,
            "dimensionItemType": "DATA_ELEMENT",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "categoryCombo": {"id": "bjDvmb4bfuf"},
            "createdBy": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "user": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "favorites": [],
            "dataSetElements": [],
            "translations": [],
            "userGroupAccesses": [],
            "dataElementGroups": [],
            "attributeValues": [],
            "userAccesses": [],
            "legendSets": [],
            "aggregationLevels": [],
        },
    ],
}


mock_indicators_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 2,
        "pageSize": 100,
    },
    "indicators": [
        {
            "code": "IN_52462",
            "lastUpdated": "2013-03-21T11:17:44.926",
            "id": "ReUHfIn0pTQ",
            "href": "https://play.dhis2.org/2.36.4/api/indicators/ReUHfIn0pTQ",
            "created": "2012-11-05T09:16:29.054",
            "name": "ANC 1-3 Dropout Rate",
            "shortName": "ANC 1-3 Dropout Rate",
            "publicAccess": "rw------",
            "displayName": "ANC 1-3 Dropout Rate",
            "description": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
            "displayShortName": "ANC 1-3 Dropout Rate",
            "externalAccess": False,
            "displayNumeratorDescription": "ANC1-ANC3",
            "denominatorDescription": "Total 1st ANC visits",
            "periodOffset": 0,
            "displayDenominatorDescription": "Total 1st ANC visits",
            "numeratorDescription": "ANC1-ANC3",
            "displayDescription": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
            "dimensionItem": "ReUHfIn0pTQ",
            "sharing": {
                "owner": "GOLswS44mh8",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "ANC 1-3 Dropout Rate",
            "url": "",
            "numerator": "#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}-#{Jtf34kNZhzP.pq2XI5kz2BY}-#{Jtf34kNZhzP.PT59n8BQbqM}",
            "denominator": "#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}",
            "annualized": False,
            "favorite": False,
            "dimensionItemType": "INDICATOR",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "indicatorType": {"id": "bWuNrMHEoZ0"},
            "createdBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "user": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "favorites": [],
            "translations": [
                {
                    "property": "SHORT_NAME",
                    "locale": "en_GB",
                    "value": "ANC Dropout Rate",
                },
                {
                    "property": "DESCRIPTION",
                    "locale": "en_GB",
                    "value": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
                },
                {
                    "property": "SHORT_NAME",
                    "locale": "fr",
                    "value": " Taux d'abandon d'ANC 1-3",
                },
                {
                    "property": "NAME",
                    "locale": "fr",
                    "value": " Taux d'abandon d'ANC 1-3",
                },
                {"property": "NAME", "locale": "en_GB", "value": "ANC Dropout Rate"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "indicatorGroups": [{"id": "oehv9EO3vP7"}, {"id": "YTeRMLGtger"}],
            "userAccesses": [],
            "dataSets": [{"id": "V8MHeZHIrcP"}, {"id": "BfMAe6Itzgt"}],
            "legendSets": [],
        },
        {
            "code": "IN_52486",
            "lastUpdated": "2016-10-10T20:45:57.873",
            "id": "Uvn6LCg7dVU",
            "href": "https://play.dhis2.org/2.36.4/api/indicators/Uvn6LCg7dVU",
            "created": "2012-11-13T12:51:32.215",
            "name": "ANC 1 Coverage",
            "shortName": "ANC 1 Coverage",
            "publicAccess": "rw------",
            "displayName": "ANC 1 Coverage",
            "aggregateExportCategoryOptionCombo": "sqGRzCziswD",
            "description": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
            "displayShortName": "ANC 1 Coverage",
            "externalAccess": False,
            "displayNumeratorDescription": "Total ANC 1 visits",
            "denominatorDescription": "Estimated number of pregnant women",
            "periodOffset": 0,
            "displayDenominatorDescription": "Estimated number of pregnant women",
            "numeratorDescription": "Total ANC 1 visits",
            "displayDescription": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
            "dimensionItem": "Uvn6LCg7dVU",
            "sharing": {
                "owner": "GOLswS44mh8",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "ANC 1 Coverage",
            "numerator": "#{fbfJHSPpUQD}",
            "denominator": "#{h0xKKjijTdI}",
            "annualized": True,
            "favorite": False,
            "dimensionItemType": "INDICATOR",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "indicatorType": {"id": "bWuNrMHEoZ0"},
            "createdBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "legendSet": {"id": "fqs276KXCXi"},
            "user": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "favorites": [],
            "translations": [
                {
                    "property": "DESCRIPTION",
                    "locale": "en_GB",
                    "value": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
                },
                {"property": "NAME", "locale": "fr", "value": "Couverture ANC 1"},
                {
                    "property": "SHORT_NAME",
                    "locale": "en_GB",
                    "value": "ANC 1 Coverage",
                },
                {"property": "NAME", "locale": "en_GB", "value": "ANC 1 Coverage"},
                {"property": "SHORT_NAME", "locale": "fr", "value": "Couverture ANC 1"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "indicatorGroups": [{"id": "oehv9EO3vP7"}, {"id": "YTeRMLGtger"}],
            "userAccesses": [],
            "dataSets": [{"id": "BfMAe6Itzgt"}],
            "legendSets": [{"id": "fqs276KXCXi"}],
        },
    ],
}


mock_indicator_types_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 5,
        "pageSize": 100,
    },
    "indicatorTypes": [
        {
            "created": "2012-11-05T20:00:33.126",
            "lastUpdated": "2014-04-22T18:41:57.387",
            "name": "Number (Factor 1)",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/JkWynlWMjJR",
            "id": "JkWynlWMjJR",
            "displayName": "Number (Factor 1)",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": True,
            "factor": 1,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Number"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per cent",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/bWuNrMHEoZ0",
            "id": "bWuNrMHEoZ0",
            "displayName": "Per cent",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 100,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per cent"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per hundred thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/vQ0dGV9EDrw",
            "id": "vQ0dGV9EDrw",
            "displayName": "Per hundred thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 100000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per hundred thousand"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per ten thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/wB7vTGTafMI",
            "id": "wB7vTGTafMI",
            "displayName": "Per ten thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 10000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per ten thousand"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.669",
            "name": "Per thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/mmey8xSvORj",
            "id": "mmey8xSvORj",
            "displayName": "Per thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 1000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per thousand"}
            ],
            "userAccesses": [],
        },
    ],
}

mock_info_json = {
    "contextPath": "https://play.dhis2.org.invalid/2.36.4",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
    "calendar": "iso8601",
    "dateFormat": "yyyy-mm-dd",
    "serverDate": "2021-11-08T16:26:36.348",
    "serverTimeZoneId": "Etc/UTC",
    "serverTimeZoneDisplayName": "Coordinated Universal Time",
    "lastAnalyticsTableSuccess": "2021-11-08T01:09:38.791",
    "intervalSinceLastAnalyticsTableSuccess": "21 h, 16 m, 57 s",
    "lastAnalyticsTableRuntime": "00:04:34.782",
    "lastSystemMonitoringSuccess": "2019-03-26T17:07:15.418",
    "lastAnalyticsTablePartitionSuccess": "2021-11-08T13:57:46.146",
    "intervalSinceLastAnalyticsTablePartitionSuccess": "8 h, 28 m, 50 s",
    "lastAnalyticsTablePartitionRuntime": "00:00:00.586",
    "version": "2.36.4-EMBARGOED",
    "revision": "e28b1d3",
    "buildTime": "2021-10-11T17:34:34.000",
    "jasperReportsVersion": "6.3.1",
    "environmentVariable": "DHIS2_HOME",
    "databaseInfo": {"spatialSupport": True},
    "encryption": False,
    "emailConfigured": False,
    "redisEnabled": False,
    "systemId": "eed3d451-4ff5-4193-b951-ffcc68954299",
    "systemName": "DHIS 2 Demo - Sierra Leone",
    "instanceBaseUrl": "https://play.dhis2.org.invalid/2.36.4",
    "clusterHostname": "",
    "isMetadataVersionEnabled": True,
    "metadataSyncEnabled": False,
}

mock_datasets_response = {
    "pager": {"page": 1, "pageCount": 1, "total": 1, "pageSize": 100},
    "dataSets": [
        {
            "lastUpdated": "2019-09-16T13:51:37.310",
            "id": "lyLU2wR22tC",
            "href": "https://play.dhis2.org.invalid/2.36.4/api/dataSets/lyLU2wR22tC",
            "created": "2012-06-10T00:36:10.036",
            "name": "ART monthly summary",
            "shortName": "ART 2010",
            "code": "DS_394131",
            "validCompleteOnly": False,
            "publicAccess": "rwr-----",
            "skipOffline": False,
            "compulsoryFieldsCompleteOnly": False,
            "formType": "CUSTOM",
            "sharing": {
                "owner": "GOLswS44mh8",
                "external": False,
                "users": {},
                "userGroups": {
                    "B6JNeAQ6akX": {"access": "r-rw----", "id": "B6JNeAQ6akX"},
                    "w900PX10L7O": {"access": "r-rw----", "id": "w900PX10L7O"},
                    "zz6XckBrLlj": {"access": "r-rw----", "id": "zz6XckBrLlj"},
                },
                "public": "rwr-----",
            },
            "displayFormName": "ART monthly summary",
            "version": 23,
            "timelyDays": 0,
            "favorite": False,
            "dimensionItemType": "REPORTING_RATE",
            "dataElementDecoration": False,
            "displayName": "ART monthly summary",
            "notifyCompletingUser": False,
            "noValueRequiresComment": False,
            "displayShortName": "ART 2010",
            "externalAccess": False,
            "fieldCombinationRequired": False,
            "periodOffset": 0,
            "renderHorizontally": False,
            "renderAsTabs": False,
            "dimensionItem": "lyLU2wR22tC",
            "mobile": False,
            "openPeriodsAfterCoEndDate": 0,
            "periodType": "Monthly",
            "openFuturePeriods": 0,
            "expiryDays": 0,
            "dataEntryForm": {"id": "rV5Un1vizeD"},
            "categoryCombo": {"id": "O4VaNks6tta"},
            "lastUpdatedBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
                "data": {"read": True, "write": True},
            },
            "createdBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "legendSet": {"id": "k1JHPfXsJND"},
            "user": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "dataSetElements": [
                {
                    "dataElement": {"id": "NV0OXpHu6x4"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
                {
                    "dataElement": {"id": "e1eDe6JsE9j"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
                {
                    "dataElement": {"id": "kVOiLDV4OC6"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
                {
                    "dataElement": {"id": "D33rH8UHKlZ"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
                {
                    "dataElement": {"id": "y6noHe7ltxY"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
                {
                    "dataElement": {"id": "E7QJ0voitk7"},
                    "dataSet": {"id": "lyLU2wR22tC"},
                },
            ],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "ART monthly summary"},
                {"property": "SHORT_NAME", "locale": "en_GB", "value": "ART 2010"},
            ],
            "dataInputPeriods": [],
            "interpretations": [],
            "userGroupAccesses": [
                {
                    "access": "r-rw----",
                    "userGroupUid": "GogLpGmkL0g",
                    "displayName": "_DATASET_Child Health Program Manager",
                    "id": "GogLpGmkL0g",
                },
                {
                    "access": "rwr-----",
                    "userGroupUid": "L4XTzgbdza3",
                    "displayName": "Wakiki",
                    "id": "L4XTzgbdza3",
                },
                {
                    "access": "r-rw----",
                    "userGroupUid": "zz6XckBrLlj",
                    "displayName": "_DATASET_System administrator (ALL)",
                    "id": "zz6XckBrLlj",
                },
            ],
            "attributeValues": [],
            "indicators": [],
            "sections": [],
            "userAccesses": [],
            "legendSets": [{"id": "k1JHPfXsJND"}],
            "favorites": [],
            "compulsoryDataElementOperands": [
                {
                    "lastUpdated": "2021-11-08T22:30:49.035",
                    "id": "NJnhOzjaLYk.rCMUTmcreqP",
                    "created": "2021-11-08T22:30:49.035",
                    "name": "ART clients with new adverse clinical event Female, >49y",
                    "shortName": "ART.CnewAdv.Clin.Ev. Female, >49y",
                    "aggregationType": "SUM",
                    "displayName": "ART clients with new adverse clinical event Female, >49y",
                    "displayShortName": "ART.CnewAdv.Clin.Ev. Female, >49y",
                    "externalAccess": False,
                    "periodOffset": 0,
                    "dimensionItem": "NJnhOzjaLYk.rCMUTmcreqP",
                    "sharing": {"external": False, "users": {}, "userGroups": {}},
                    "displayFormName": "ART clients with new adverse clinical event Female, >49y",
                    "favorite": False,
                    "dimensionItemType": "DATA_ELEMENT_OPERAND",
                    "access": {
                        "read": True,
                        "update": True,
                        "externalize": False,
                        "delete": True,
                        "write": True,
                        "manage": True,
                    },
                    "categoryOptionCombo": {"id": "rCMUTmcreqP"},
                    "dataElement": {"id": "NJnhOzjaLYk"},
                    "favorites": [],
                    "translations": [],
                    "userGroupAccesses": [],
                    "attributeValues": [],
                    "userAccesses": [],
                    "legendSets": [],
                },
            ],
            "organisationUnits": [{"id": "y77LiPqLMoq"}, {"id": "egv5Es0QlQP"}],
        }
    ],
}

mock_orgunits_response = {
    "pager": {"page": 1, "pageCount": 1, "total": 2, "pageSize": 100},
    "organisationUnits": [
        {
            "lastUpdated": "2017-05-22T15:21:48.515",
            "id": "Rp268JB6Ne4",
            "href": "https://play.dhis2.org/2.36.4/api/organisationUnits/Rp268JB6Ne4",
            "level": 4,
            "created": "2012-02-17T15:54:39.987",
            "name": "Adonkia CHP",
            "shortName": "Adonkia CHP",
            "code": "OU_651071",
            "leaf": True,
            "path": "/ImspTQPwCqd/at6UHUQatSo/qtr8GGlm4gg/Rp268JB6Ne4",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "displayFormName": "Adonkia CHP",
            "favorite": False,
            "dimensionItemType": "ORGANISATION_UNIT",
            "displayName": "Adonkia CHP",
            "displayShortName": "Adonkia CHP",
            "externalAccess": False,
            "periodOffset": 0,
            "openingDate": "2010-01-01T00:00:00.000",
            "dimensionItem": "Rp268JB6Ne4",
            "parent": {"id": "qtr8GGlm4gg"},
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "children": [],
            "translations": [],
            "organisationUnitGroups": [{"id": "f25dqv3Y7Z0"}],
            "ancestors": [
                {"id": "ImspTQPwCqd"},
                {"id": "at6UHUQatSo"},
                {"id": "qtr8GGlm4gg"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "users": [],
            "userAccesses": [],
            "dataSets": [
                {"id": "N4fIX1HL3TQ"},
                {"id": "Y8gAn9DfAGU"},
                {"id": "pBOMPrpg1QX"},
                {"id": "YZhd4nu3mzY"},
                {"id": "TuL8IOPzpHh"},
                {"id": "QX4ZTUbOt3a"},
                {"id": "Nyh6laLdBEJ"},
                {"id": "EKWVBc5C0ms"},
                {"id": "ULowA8V3ucd"},
                {"id": "YFTk3VdO9av"},
                {"id": "eZDhcZi6FLP"},
                {"id": "j38YW1Am7he"},
                {"id": "V8MHeZHIrcP"},
                {"id": "aLpVgfXiz0f"},
                {"id": "Lpw6GcnTrmS"},
                {"id": "VTdjfLXXmoi"},
                {"id": "rsyjyJmYD4J"},
                {"id": "BfMAe6Itzgt"},
                {"id": "SF8FDSqw30D"},
                {"id": "ce7DSxx5H2I"},
                {"id": "PLq9sJluXvc"},
            ],
            "legendSets": [],
            "programs": [
                {"id": "q04UBOqq3rp"},
                {"id": "kla3mAPgvCH"},
                {"id": "M3xtLkYBlKI"},
                {"id": "MoUd5BTQ3lY"},
                {"id": "uy2gU8kT1jF"},
                {"id": "VBqh0ynB2wv"},
                {"id": "eBAyeGv0exc"},
                {"id": "qDkgAbB5Jlk"},
                {"id": "bMcwwoVnbSR"},
                {"id": "lxAQ7Zs9VYR"},
                {"id": "IpHINAT79UW"},
                {"id": "WSGAb5XwJ3Y"},
                {"id": "ur1Edk5Oe2n"},
            ],
            "favorites": [],
        },
        {
            "lastUpdated": "2017-05-22T15:21:48.518",
            "id": "cDw53Ej8rju",
            "href": "https://play.dhis2.org/2.36.4/api/organisationUnits/cDw53Ej8rju",
            "level": 4,
            "created": "2012-02-17T15:54:39.987",
            "name": "Afro Arab Clinic",
            "shortName": "Afro Arab Clinic",
            "code": "OU_278371",
            "leaf": True,
            "path": "/ImspTQPwCqd/at6UHUQatSo/qtr8GGlm4gg/cDw53Ej8rju",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "displayFormName": "Afro Arab Clinic",
            "favorite": False,
            "dimensionItemType": "ORGANISATION_UNIT",
            "displayName": "Afro Arab Clinic",
            "displayShortName": "Afro Arab Clinic",
            "externalAccess": False,
            "periodOffset": 0,
            "openingDate": "2008-01-01T00:00:00.000",
            "dimensionItem": "cDw53Ej8rju",
            "parent": {"id": "qtr8GGlm4gg"},
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "children": [],
            "translations": [
                {
                    "property": "SHORT_NAME",
                    "locale": "en_GB",
                    "value": "Afro Arab Clinic",
                },
                {"property": "NAME", "locale": "en_GB", "value": "Afro Arab Clinic"},
            ],
            "organisationUnitGroups": [{"id": "f25dqv3Y7Z0"}, {"id": "RXL3lPSK8oG"}],
            "ancestors": [
                {"id": "ImspTQPwCqd"},
                {"id": "at6UHUQatSo"},
                {"id": "qtr8GGlm4gg"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "users": [],
            "userAccesses": [],
            "dataSets": [
                {"id": "Y8gAn9DfAGU"},
                {"id": "pBOMPrpg1QX"},
                {"id": "QX4ZTUbOt3a"},
                {"id": "EKWVBc5C0ms"},
                {"id": "lyLU2wR22tC"},
                {"id": "j38YW1Am7he"},
                {"id": "V8MHeZHIrcP"},
                {"id": "VTdjfLXXmoi"},
                {"id": "ce7DSxx5H2I"},
                {"id": "PLq9sJluXvc"},
                {"id": "N4fIX1HL3TQ"},
                {"id": "YZhd4nu3mzY"},
                {"id": "TuL8IOPzpHh"},
                {"id": "EDzMBk0RRji"},
                {"id": "Nyh6laLdBEJ"},
                {"id": "ULowA8V3ucd"},
                {"id": "YFTk3VdO9av"},
                {"id": "eZDhcZi6FLP"},
                {"id": "OsPTWNqq26W"},
                {"id": "aLpVgfXiz0f"},
                {"id": "Lpw6GcnTrmS"},
                {"id": "rsyjyJmYD4J"},
                {"id": "BfMAe6Itzgt"},
                {"id": "SF8FDSqw30D"},
                {"id": "Rl58JxmKJo2"},
            ],
            "legendSets": [],
            "programs": [
                {"id": "q04UBOqq3rp"},
                {"id": "kla3mAPgvCH"},
                {"id": "M3xtLkYBlKI"},
                {"id": "MoUd5BTQ3lY"},
                {"id": "uy2gU8kT1jF"},
                {"id": "VBqh0ynB2wv"},
                {"id": "eBAyeGv0exc"},
                {"id": "qDkgAbB5Jlk"},
                {"id": "bMcwwoVnbSR"},
                {"id": "lxAQ7Zs9VYR"},
                {"id": "IpHINAT79UW"},
                {"id": "WSGAb5XwJ3Y"},
                {"id": "ur1Edk5Oe2n"},
            ],
            "favorites": [],
        },
    ],
}
