# Generated by Django 5.2.4 on 2025-09-16 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_options_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Lowercase alphanumeric characters and hyphens only",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Tag name must be at least 2 characters long"
                    ),
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+(-[a-z0-9]+)*$",
                        message="Tag name must contain only lowercase letters, numbers, and single hyphens (no consecutive hyphens, no leading/trailing hyphens)",
                    ),
                ],
            ),
        ),
    ]
