mock_data_elements_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 2,
        "pageSize": 100,
    },
    "dataElements": [
        {
            "code": "EMM_TYY_HXX",
            "lastUpdated": "2015-10-14T13:36:36.040",
            "id": "m3TSrzUIVlm",
            "href": "https://play.dhis2.org/demo/api/dataElements/m3TSrzUIVlm",
            "created": "2014-11-29T20:30:04.338",
            "name": "WHOMCH Uterotonics given",
            "shortName": "Uterotonics given",
            "aggregationType": "SUM",
            "domainType": "TRACKER",
            "displayName": "WHOMCH Uterotonics given",
            "publicAccess": "rw------",
            "description": "If person was treated with uterotonics",
            "displayShortName": "Uterotonics given",
            "externalAccess": False,
            "periodOffset": 0,
            "valueType": "BOOLEAN",
            "formName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "displayDescription": "If person was treated with uterotonics",
            "dimensionItem": "m3XQrgadVK9",
            "sharing": {
                "owner": "xE7jOejl9FI",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "zeroIsSignificant": False,
            "favorite": False,
            "optionSetValue": False,
            "dimensionItemType": "DATA_ELEMENT",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "categoryCombo": {"id": "bjDvmb4bfuf"},
            "createdBy": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "user": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "favorites": [],
            "dataSetElements": [],
            "translations": [],
            "userGroupAccesses": [],
            "dataElementGroups": [],
            "attributeValues": [],
            "userAccesses": [],
            "legendSets": [],
            "aggregationLevels": [],
        },
        {
            "code": "EMM_TYY_HX2",
            "lastUpdated": "2015-10-14T13:36:36.040",
            "id": "m3TSrzUIVl3",
            "href": "https://play.dhis2.org/demo/api/dataElements/m3TSrzUIVl3",
            "created": "2014-11-29T20:30:04.338",
            "name": "WHOMCH Uterotonics given",
            "shortName": "Uterotonics given",
            "aggregationType": "SUM",
            "domainType": "TRACKER",
            "displayName": "WHOMCH Uterotonics given",
            "publicAccess": "rw------",
            "description": "If person was treated with uterotonics",
            "displayShortName": "Uterotonics given",
            "externalAccess": False,
            "periodOffset": 0,
            "valueType": "BOOLEAN",
            "formName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "displayDescription": "If person was treated with uterotonics",
            "dimensionItem": "m3XQrgadVK9",
            "sharing": {
                "owner": "xE7jOejl9FI",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "Therapeutic uterotonics given for management of postpartum haemorrhage",
            "zeroIsSignificant": False,
            "favorite": False,
            "optionSetValue": False,
            "dimensionItemType": "DATA_ELEMENT",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "categoryCombo": {"id": "bjDvmb4bfuf"},
            "createdBy": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "user": {
                "displayName": "John Traore",
                "name": "John Traore",
                "id": "xE7jOejl9FI",
                "username": "admin",
            },
            "favorites": [],
            "dataSetElements": [],
            "translations": [],
            "userGroupAccesses": [],
            "dataElementGroups": [],
            "attributeValues": [],
            "userAccesses": [],
            "legendSets": [],
            "aggregationLevels": [],
        },
    ],
}


mock_indicators_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 2,
        "pageSize": 100,
    },
    "indicators": [
        {
            "code": "IN_52462",
            "lastUpdated": "2013-03-21T11:17:44.926",
            "id": "ReUHfIn0pTQ",
            "href": "https://play.dhis2.org/2.36.4/api/indicators/ReUHfIn0pTQ",
            "created": "2012-11-05T09:16:29.054",
            "name": "ANC 1-3 Dropout Rate",
            "shortName": "ANC 1-3 Dropout Rate",
            "publicAccess": "rw------",
            "displayName": "ANC 1-3 Dropout Rate",
            "description": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
            "displayShortName": "ANC 1-3 Dropout Rate",
            "externalAccess": False,
            "displayNumeratorDescription": "ANC1-ANC3",
            "denominatorDescription": "Total 1st ANC visits",
            "periodOffset": 0,
            "displayDenominatorDescription": "Total 1st ANC visits",
            "numeratorDescription": "ANC1-ANC3",
            "displayDescription": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
            "dimensionItem": "ReUHfIn0pTQ",
            "sharing": {
                "owner": "GOLswS44mh8",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "ANC 1-3 Dropout Rate",
            "url": "",
            "numerator": "#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}-#{Jtf34kNZhzP.pq2XI5kz2BY}-#{Jtf34kNZhzP.PT59n8BQbqM}",
            "denominator": "#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}",
            "annualized": False,
            "favorite": False,
            "dimensionItemType": "INDICATOR",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "indicatorType": {"id": "bWuNrMHEoZ0"},
            "createdBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "user": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "favorites": [],
            "translations": [
                {
                    "property": "SHORT_NAME",
                    "locale": "en_GB",
                    "value": "ANC Dropout Rate",
                },
                {
                    "property": "DESCRIPTION",
                    "locale": "en_GB",
                    "value": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
                },
                {
                    "property": "SHORT_NAME",
                    "locale": "fr",
                    "value": " Taux d'abandon d'ANC 1-3",
                },
                {
                    "property": "NAME",
                    "locale": "fr",
                    "value": " Taux d'abandon d'ANC 1-3",
                },
                {"property": "NAME", "locale": "en_GB", "value": "ANC Dropout Rate"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "indicatorGroups": [{"id": "oehv9EO3vP7"}, {"id": "YTeRMLGtger"}],
            "userAccesses": [],
            "dataSets": [{"id": "V8MHeZHIrcP"}, {"id": "BfMAe6Itzgt"}],
            "legendSets": [],
        },
        {
            "code": "IN_52486",
            "lastUpdated": "2016-10-10T20:45:57.873",
            "id": "Uvn6LCg7dVU",
            "href": "https://play.dhis2.org/2.36.4/api/indicators/Uvn6LCg7dVU",
            "created": "2012-11-13T12:51:32.215",
            "name": "ANC 1 Coverage",
            "shortName": "ANC 1 Coverage",
            "publicAccess": "rw------",
            "displayName": "ANC 1 Coverage",
            "aggregateExportCategoryOptionCombo": "sqGRzCziswD",
            "description": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
            "displayShortName": "ANC 1 Coverage",
            "externalAccess": False,
            "displayNumeratorDescription": "Total ANC 1 visits",
            "denominatorDescription": "Estimated number of pregnant women",
            "periodOffset": 0,
            "displayDenominatorDescription": "Estimated number of pregnant women",
            "numeratorDescription": "Total ANC 1 visits",
            "displayDescription": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
            "dimensionItem": "Uvn6LCg7dVU",
            "sharing": {
                "owner": "GOLswS44mh8",
                "external": False,
                "users": {},
                "userGroups": {},
                "public": "rw------",
            },
            "displayFormName": "ANC 1 Coverage",
            "numerator": "#{fbfJHSPpUQD}",
            "denominator": "#{h0xKKjijTdI}",
            "annualized": True,
            "favorite": False,
            "dimensionItemType": "INDICATOR",
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "indicatorType": {"id": "bWuNrMHEoZ0"},
            "createdBy": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "legendSet": {"id": "fqs276KXCXi"},
            "user": {
                "displayName": "Tom Wakiki",
                "name": "Tom Wakiki",
                "id": "GOLswS44mh8",
                "username": "system",
            },
            "favorites": [],
            "translations": [
                {
                    "property": "DESCRIPTION",
                    "locale": "en_GB",
                    "value": "Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.",
                },
                {"property": "NAME", "locale": "fr", "value": "Couverture ANC 1"},
                {
                    "property": "SHORT_NAME",
                    "locale": "en_GB",
                    "value": "ANC 1 Coverage",
                },
                {"property": "NAME", "locale": "en_GB", "value": "ANC 1 Coverage"},
                {"property": "SHORT_NAME", "locale": "fr", "value": "Couverture ANC 1"},
            ],
            "userGroupAccesses": [],
            "attributeValues": [],
            "indicatorGroups": [{"id": "oehv9EO3vP7"}, {"id": "YTeRMLGtger"}],
            "userAccesses": [],
            "dataSets": [{"id": "BfMAe6Itzgt"}],
            "legendSets": [{"id": "fqs276KXCXi"}],
        },
    ],
}


mock_indicator_types_response = {
    "pager": {
        "page": 1,
        "pageCount": 1,
        "total": 5,
        "pageSize": 100,
    },
    "indicatorTypes": [
        {
            "created": "2012-11-05T20:00:33.126",
            "lastUpdated": "2014-04-22T18:41:57.387",
            "name": "Number (Factor 1)",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/JkWynlWMjJR",
            "id": "JkWynlWMjJR",
            "displayName": "Number (Factor 1)",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": True,
            "factor": 1,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Number"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per cent",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/bWuNrMHEoZ0",
            "id": "bWuNrMHEoZ0",
            "displayName": "Per cent",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 100,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per cent"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per hundred thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/vQ0dGV9EDrw",
            "id": "vQ0dGV9EDrw",
            "displayName": "Per hundred thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 100000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per hundred thousand"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.670",
            "name": "Per ten thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/wB7vTGTafMI",
            "id": "wB7vTGTafMI",
            "displayName": "Per ten thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 10000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per ten thousand"}
            ],
            "userAccesses": [],
        },
        {
            "created": "2011-12-24T12:24:22.592",
            "lastUpdated": "2013-03-15T16:08:57.669",
            "name": "Per thousand",
            "href": "https://play.dhis2.org/2.36.4/api/indicatorTypes/mmey8xSvORj",
            "id": "mmey8xSvORj",
            "displayName": "Per thousand",
            "sharing": {"external": False, "users": {}, "userGroups": {}},
            "externalAccess": False,
            "number": False,
            "factor": 1000,
            "favorite": False,
            "access": {
                "read": True,
                "update": True,
                "externalize": False,
                "delete": True,
                "write": True,
                "manage": True,
            },
            "favorites": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "translations": [
                {"property": "NAME", "locale": "en_GB", "value": "Per thousand"}
            ],
            "userAccesses": [],
        },
    ],
}
