# Generated by Django 3.2 on 2021-04-19 19:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposerEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hexa_name", models.CharField(blank=True, max_length=200)),
                ("hexa_short_name", models.CharField(blank=True, max_length=100)),
                ("hexa_description", models.TextField(blank=True)),
                (
                    "hexa_countries",
                    django_countries.fields.CountryField(
                        blank=True, max_length=746, multiple=True
                    ),
                ),
                ("hexa_last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("hexa_active_from", models.DateTimeField(blank=True, null=True)),
                ("hexa_active_to", models.DateTimeField(blank=True, null=True)),
                ("hexa_created_at", models.DateTimeField(auto_now_add=True)),
                ("hexa_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("api_url", models.URLField()),
            ],
            options={
                "verbose_name": "S3 Bucket",
                "ordering": ("hexa_name",),
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_account_email", models.EmailField(max_length=254)),
                ("service_account_key", models.JSONField()),
                ("oidc_target_audience", models.CharField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airflow_credential_set",
                        to="user_management.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "S3 Credentials",
                "verbose_name_plural": "S3 Credentials",
                "ordering": ("service_account_email",),
            },
        ),
        migrations.CreateModel(
            name="ComposerEnvironmentPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "composer_environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_airflow.composerenvironment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="composerenvironment",
            name="api_credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="connector_airflow.credentials",
            ),
        ),
        migrations.AddField(
            model_name="composerenvironment",
            name="hexa_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_management.organization",
            ),
        ),
    ]
