# Generated by Django 3.2 on 2021-04-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="composerenvironment",
            options={"ordering": ("hexa_name",), "verbose_name": "Airflow environment"},
        ),
        migrations.AlterModelOptions(
            name="credentials",
            options={
                "ordering": ("service_account_email",),
                "verbose_name": "Airflow Credentials",
                "verbose_name_plural": "Airflow Credentials",
            },
        ),
    ]
