# Generated by Django 3.2 on 2021-04-21 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0004_basic_dag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credentials",
            old_name="service_account_key",
            new_name="service_account_key_data",
        ),
        migrations.CreateModel(
            name="DAGConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("config_data", models.JSONField(default=dict)),
                (
                    "dag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_airflow.dag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
