# Generated by Django 3.2 on 2021-04-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0005_dag_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dag",
            options={"ordering": ["dag_id"], "verbose_name": "DAG"},
        ),
        migrations.AlterModelOptions(
            name="dagconfig",
            options={"verbose_name": "DAG config"},
        ),
        migrations.RenameField(
            model_name="dag",
            old_name="hexa_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="dag",
            old_name="hexa_updated_at",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_countries",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_description",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_last_synced_at",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_locale",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_name",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_owner",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="hexa_short_name",
        ),
    ]
