# Generated by Django 3.2.6 on 2021-09-14 14:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hexa.core.models.behaviors


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0006_alter_clusterpermission_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAGRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_refreshed_at", models.DateTimeField(null=True)),
                ("run_id", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("execution_date", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_refreshed_at",),
            },
            bases=(models.Model, hexa.core.models.behaviors.WithStatus),
        ),
        migrations.AlterModelOptions(
            name="cluster",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="cluster",
            old_name="airflow_api_url",
            new_name="api_url",
        ),
        migrations.RenameField(
            model_name="cluster",
            old_name="airflow_web_url",
            new_name="web_url",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="airflow_name",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="description",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="description",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="dagconfig",
            name="short_name",
        ),
        migrations.AddField(
            model_name="cluster",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="DAGConfigRun",
        ),
        migrations.AddField(
            model_name="dagrun",
            name="dag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connector_airflow.dag"
            ),
        ),
        migrations.AddField(
            model_name="dagrun",
            name="dag_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="connector_airflow.dagconfig",
            ),
        ),
    ]
