# Generated by Django 3.2 on 2021-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0006_fine_tuning"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagconfig",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
