# Generated by Django 3.2 on 2021-04-21 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0007_fine_tuning_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAGConfigRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("execution_date", models.DateTimeField()),
                (
                    "dag_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_airflow.dagconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
