# Generated by Django 3.2 on 2021-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0008_dag_config_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagconfigrun",
            name="last_refreshed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
