# Generated by Django 3.2 on 2021-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0009_dag_config_run_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagconfigrun",
            name="state",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
