# Generated by Django 3.2 on 2021-04-23 07:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        ("connector_airflow", "0010_dag_config_run_refresh_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dag",
            options={"ordering": ["airflow_id"], "verbose_name": "DAG"},
        ),
        migrations.RenameField(
            model_name="dag",
            old_name="dag_id",
            new_name="airflow_id",
        ),
        migrations.RenameField(
            model_name="dag",
            old_name="created_at",
            new_name="hexa_created_at",
        ),
        migrations.RenameField(
            model_name="dag",
            old_name="updated_at",
            new_name="hexa_updated_at",
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_active_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_active_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_countries",
            field=django_countries.fields.CountryField(
                blank=True, max_length=746, multiple=True
            ),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="dag",
            name="hexa_short_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
