# Generated by Django 3.2 on 2021-04-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0011_pipelines_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dagconfigrun",
            old_name="last_refreshed_at",
            new_name="hexa_last_refreshed_at",
        ),
    ]
