# Generated by Django 3.2 on 2021-04-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0012_pipelines_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dagconfig",
            name="last_run_at",
        ),
    ]
