# Generated by Django 3.2.7 on 2021-10-27 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0014_support_sample_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dagrun",
            old_name="used_config",
            new_name="conf",
        ),
    ]
