# Generated by Django 3.2.7 on 2021-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0017_cluster_auto_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dag",
            name="sample_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="dagrun",
            name="conf",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
