# Generated by Django 4.0 on 2022-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0023_alter_dagtemplate_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="dag",
            name="sample_config",
        ),
        migrations.AddField(
            model_name="dagauthorizeddatasource",
            name="label",
            field=models.CharField(default="datasource", max_length=200),
        ),
        migrations.AddField(
            model_name="dagtemplate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dagtemplate",
            name="sample_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
