# Generated by Django 4.0.2 on 2022-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_airflow",
            "0024_remove_dag_description_remove_dag_sample_config_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dagrun",
            name="webhook_token",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
