# Generated by Django 4.0.2 on 2022-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagrun",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
