# Generated by Django 4.0.2 on 2022-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dagauthorizeddatasource",
            old_name="label",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="dagauthorizeddatasource",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
