# Generated by Django 4.0.2 on 2022-03-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0028_dagrun_favorite_unique"),
        ("connector_airflow", "0028_limit_dagauthorizeddatasource_datasource_type"),
    ]

    operations = []
