# Generated by Django 4.0.3 on 2022-04-08 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_user_management_to_identity_1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_airflow", "0031_limit_dagauthorizeddatasource_datasource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagpermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dagpermission",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
    ]
