# Generated by Django 4.0.3 on 2022-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0032_permissions_user_or_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagpermission",
            name="mode",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("EDITOR", "Editor")],
                default="EDITOR",
                max_length=200,
            ),
        ),
    ]
