# Generated by Django 4.0.6 on 2022-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0033_dagrun_current_progress_dagrun_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dag",
            name="form_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
