# Generated by Django 5.0.2 on 2024-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0035_alter_dag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dagrun",
            name="state",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("queued", "Queued"),
                    ("terminating", "terminating"),
                    ("stopped", "Stopped"),
                ],
                max_length=200,
            ),
        ),
    ]
