# Generated by Django 5.1.5 on 2025-02-17 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("superset", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supersetinstance",
            old_name="admin_password",
            new_name="api_password",
        ),
        migrations.RenameField(
            model_name="supersetinstance",
            old_name="admin_username",
            new_name="api_username",
        ),
    ]
