# Generated by Django 3.2.6 on 2021-08-10 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
