# Generated by Django 3.2.7 on 2021-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_tos",
            field=models.BooleanField(default=False),
        ),
    ]
