# Generated by Django 4.0.6 on 2022-08-17 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0011_unique_fine_tuning"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="feature",
            table="identity_feature",
        ),
        migrations.AlterModelTable(
            name="featureflag",
            table="identity_featureflag",
        ),
        migrations.AlterModelTable(
            name="membership",
            table="identity_membership",
        ),
        migrations.AlterModelTable(
            name="organization",
            table="identity_organization",
        ),
        migrations.AlterModelTable(
            name="team",
            table="identity_team",
        ),
        migrations.AlterModelTable(
            name="user",
            table="identity_user",
        ),
    ]
