# Generated by Django 4.0.4 on 2022-06-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0011_unique_fine_tuning"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signed_up_from",
            field=models.URLField(
                blank=True, help_text="The URL of the page the user has used to sign up"
            ),
        ),
    ]
