# Generated by Django 4.0.6 on 2022-09-01 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0012_rename_identity_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name", "email"]},
        ),
    ]
