# Generated by Django 4.0.4 on 2022-06-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0012_user_signed_up_from"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="feature",
            table="identity_feature",
        ),
        migrations.AlterModelTable(
            name="featureflag",
            table="identity_featureflag",
        ),
        migrations.AlterModelTable(
            name="membership",
            table="identity_membership",
        ),
        migrations.AlterModelTable(
            name="organization",
            table="identity_organization",
        ),
        migrations.AlterModelTable(
            name="team",
            table="identity_team",
        ),
        migrations.AlterModelTable(
            name="user",
            table="identity_user",
        ),
    ]
