# Generated by Django 5.0.6 on 2024-07-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0019_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="analytics_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
