# Generated by Django 3.2 on 2021-04-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="dhis2_url",
        ),
        migrations.AddField(
            model_name="instance",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
