# Generated by Django 3.2.3 on 2021-05-24 16:17

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0004_dhis2_extract_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_url", models.URLField()),
                ("username", hexa.core.models.cryptography.EncryptedTextField()),
                ("password", hexa.core.models.cryptography.EncryptedTextField()),
            ],
            options={
                "verbose_name": "DHIS2 API Credentials",
                "verbose_name_plural": "DHIS2 API Credentials",
                "ordering": ("api_url",),
            },
        ),
        migrations.RemoveField(
            model_name="instance",
            name="dhis2_api_password",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="dhis2_api_url",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="dhis2_api_username",
        ),
        migrations.AddField(
            model_name="instance",
            name="api_credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="connector_dhis2.credentials",
            ),
        ),
    ]
