# Generated by Django 3.2.5 on 2021-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_tags"),
        ("connector_dhis2", "0010_tags_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="tags",
            field=models.ManyToManyField(blank=True, to="catalog.Tag"),
        ),
    ]
