# Generated by Django 3.2.7 on 2021-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0019_alter_instance_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="auto_sync",
            field=models.BooleanField(default=True),
        ),
    ]
