# Generated by Django 3.2.7 on 2021-11-27 08:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hexa.catalog.models
import hexa.core.models.path


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0020_instance_auto_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dhis2_id", models.CharField(max_length=200)),
                ("name", models.TextField()),
                ("short_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("external_access", models.BooleanField()),
                ("favorite", models.BooleanField()),
                ("created", models.DateTimeField()),
                ("last_updated", models.DateTimeField()),
                ("code", models.CharField(blank=True, max_length=100)),
                ("path", hexa.core.models.path.PathField()),
                ("leaf", models.BooleanField()),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_dhis2.instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHIS2 Organisation Unit",
                "ordering": ("name",),
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
    ]
