# Generated by Django 4.0.2 on 2022-03-15 16:16

from django.db import migrations, models
from slugify import slugify


def forwards_func(apps, schema_editor):
    Instance = apps.get_model("connector_dhis2", "Instance")
    for instance in Instance.objects.all():
        instance.slug = slugify(instance.name, stopwords=["dhis2", "instance"])
        instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0023_instance_verbose_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instancepermission",
            name="enable_notebooks_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Should the user have access to the API credentials?",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
