# Generated by Django 4.0.2 on 2022-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0024_dhis2_instance_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
