# Generated by Django 4.0.6 on 2022-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0028_instance_public"),
    ]

    operations = []
