# Generated by Django 4.0.6 on 2022-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0029_collections"),
    ]

    operations = []
