# Generated by Django 4.1.3 on 2023-01-20 14:22

from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_workspace_members_alter_workspace_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDBConfig",
            fields=[
                (
                    "_singleton",
                    models.BooleanField(
                        default=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("hostname", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                (
                    "password",
                    hexa.core.models.cryptography.EncryptedTextField(max_length=200),
                ),
                ("port", models.IntegerField(default=5432)),
            ],
        ),
    ]
