# Generated by Django 4.1.3 on 2023-02-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_postgresql", "0010_database_public"),
        ("workspaces", "0005_workspace_members_alter_workspace_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="database",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="connector_postgresql.database",
            ),
        ),
    ]
