# Generated by Django 4.1.3 on 2023-02-06 13:33

import re

import django.core.validators
from django.db import migrations, models


def migrate_workspace_slug(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    from hexa.workspaces.models import create_workspace_slug

    for workspace in Workspace.objects.filter(slug=None).all():
        workspace.slug = create_workspace_slug(workspace.name)
        workspace.save()


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0006_workspace_slug"),
    ]

    operations = [
        migrations.RunPython(migrate_workspace_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workspace",
            name="slug",
            field=models.CharField(
                editable=False,
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
