# Generated by Django 4.1.3 on 2023-01-25 09:02

from django.db import migrations

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0007_alter_workspaceconnection_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspaceconnection",
            old_name="_slug",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="workspaceconnectionfield",
            old_name="name",
            new_name="code",
        ),
        migrations.AlterField(
            model_name="workspaceconnectionfield",
            name="value",
            field=hexa.core.models.cryptography.EncryptedTextField(blank=True),
        ),
    ]
