# Generated by Django 4.1.3 on 2023-01-25 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0008_rename__slug_workspaceconnection_slug_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkspaceConnection",
            new_name="Connection",
        ),
        migrations.RenameModel(
            old_name="WorkspaceConnectionField",
            new_name="ConnectionField",
        ),
    ]
