# Generated by Django 4.1.3 on 2023-01-27 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0011_alter_connection_slug_alter_connectionfield_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connectionfield",
            unique_together={("connection", "code")},
        ),
    ]
