# Generated by Django 4.1.3 on 2023-01-27 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0012_alter_connectionfield_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectionfield",
            options={},
        ),
    ]
