# Generated by Django 4.1.3 on 2023-02-20 15:20

from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0015_alter_connectionfield_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="db_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="db_password",
            field=hexa.core.models.cryptography.EncryptedTextField(blank=True),
        ),
    ]
