# Generated by Django 4.1.3 on 2023-02-17 16:45

from django.db import migrations

import hexa.core.models.cryptography


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0015_alter_connectionfield_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="db_password",
            field=hexa.core.models.cryptography.EncryptedTextField(null=True),
        ),
    ]
