# Generated by Django 4.1.3 on 2023-02-20 16:06

from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0016_workspace_db_name_workspace_db_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="db_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="db_password",
            field=hexa.core.models.cryptography.EncryptedTextField(null=True),
        ),
    ]
