# Generated by Django 4.1.3 on 2023-03-07 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0018_alter_connectionfield_user"),
        ("workspaces", "0019_workspace_membership_hash_unique"),
    ]

    operations = []
