# Generated by Django 4.1.3 on 2023-03-10 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0021_merge_20230307_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
    ]
