# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0023_workspace_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="db_name",
            field=models.CharField(max_length=63, null=True),
        ),
    ]
