# Generated by Django 4.1.7 on 2023-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0026_alter_workspace_db_name_alter_workspace_db_password"),
        (
            "workspaces",
            "0026_workspacemembership_token_squashed_0028_alter_workspacemembership_access_token",
        ),
    ]

    operations = []
