# Generated by Django 4.1.7 on 2023-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0030_fields_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="connection_type",
            field=models.TextField(
                choices=[
                    ("S3", "S3 Bucket"),
                    ("GCS", "GCS Bucket"),
                    ("POSTGRESQL", "PostgreSQL DB"),
                    ("CUSTOM", "Custom"),
                    ("DHIS2", "DHIS2 Instance"),
                    ("IASO", "IASO Instance"),
                ],
                max_length=32,
            ),
        ),
    ]
