# Generated by Django 4.1.7 on 2023-09-21 14:52

from django.db import migrations


def generate_tokens(apps, schema_editor):
    # Get the model from the versioned app registry
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")

    # Filter the instances without access_token
    memberships_without_token = WorkspaceMembership.objects.filter(
        access_token__isnull=True
    )

    for membership in memberships_without_token:
        membership.generate_access_token()
        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0036_service_account_key_migration"),
    ]

    operations = []
