# Generated by Django 4.1.7 on 2023-09-21 15:44

from django.db import migrations, models


def generate_tokens(apps, schema_editor):
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")

    # Filter the instances without access_token
    memberships_without_token = WorkspaceMembership.objects.filter(
        models.Q(access_token__isnull=True) | models.Q(access_token="")
    )

    for membership in memberships_without_token:
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0036_service_account_key_migration"),
    ]

    operations = [
        migrations.RunPython(generate_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workspacemembership",
            name="access_token",
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="notebooks_server_hash",
            field=models.TextField(unique=True),
        ),
    ]
