# Generated by Django 4.1.7 on 2023-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0037_add_missing_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="access_token",
            field=models.TextField(
                blank=True,
                help_text="Access token that can be used to interact with the OpenHexa API (will be generated automatically, set to empty to regenerate a new token)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="notebooks_server_hash",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Can be used to identify a notebook server for a given user and workspace (will be generated automatically)",
                unique=True,
            ),
        ),
    ]
