# Generated by Django 4.1.7 on 2023-10-09 10:29

from django.db import migrations


def rename_iaso_connections_api_url_field(apps, schema_editor):
    Connection = apps.get_model("workspaces", "Connection")

    iaso_connections = Connection.objects.filter(connection_type="IASO")
    for conn in iaso_connections:
        conn.fields.filter(code="api_url").update(code="url")


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0037_alter_workspacemembership_access_token_and_more"),
    ]

    operations = [
        migrations.RunPython(
            rename_iaso_connections_api_url_field,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
