# Generated by Django 4.1.7 on 2023-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0037_alter_workspacemembership_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="docker_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
