# Generated by Django 4.2.6 on 2023-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0038_rename_iaso_service_url"),
        ("core", "0009_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="email",
            field=models.EmailField(db_collation="case_insensitive", max_length=254),
        ),
    ]
