# Generated by Django 4.2.6 on 2023-11-22 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0040_s3_connection_secret_fields"),
        ("workspaces", "0040_workspace_docker_image"),
    ]

    operations = []
