# Generated by Django 4.2.6 on 2023-11-23 15:40

from django.db import migrations


def update_workspace_created_by(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")

    workspaces = []
    for workspace in Workspace.objects.all():
        try:
            workspace.created_by = (
                workspace.workspacemembership_set.order_by("created_at").first().user
            )
            workspaces.append(workspace)
        except Exception:
            pass

    Workspace.objects.bulk_update(workspaces, ["created_by"])


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0041_merge_20231122_1640"),
    ]

    operations = [
        migrations.RunPython(
            update_workspace_created_by,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
