# Generated by Django 4.2.17 on 2025-01-14 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Connection"),
                migrations.DeleteModel(name="ConnectionField"),
            ],
            database_operations=[],
        ),
    ]
