# Generated by Django 5.0.3 on 2024-05-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embeds", "0001_initial"),
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="homepage_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="embeds.webpage",
            ),
        ),
    ]
