# Generated by Django 5.0.3 on 2024-05-22 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0045_workspace_homepage_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="homepage_page",
            new_name="homepage",
        ),
    ]
