# Generated by Django 3.2.3 on 2021-05-27 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_minor_fine_tuning"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogindex",
            name="index_ptr",
        ),
        migrations.RemoveField(
            model_name="catalogindexpermission",
            name="catalog_index",
        ),
        migrations.RemoveField(
            model_name="catalogindexpermission",
            name="team",
        ),
    ]
