# Generated by Django 3.2.6 on 2021-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_metadata_rf_4"),
        ("catalog", "0011_metadata_rf_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.Tag"),
        ),
    ]
