# Generated by Django 3.2.6 on 2021-08-31 08:56

import django_ltree.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_validation_and_blanks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="path",
            field=django_ltree.fields.PathField(blank=True, null=True),
        ),
    ]
