# Generated by Django 3.2.6 on 2021-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_custom_path_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="search",
            field=models.TextField(blank=True),
        ),
    ]
