# Generated by Django 3.2.6 on 2021-09-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user_management", "0003_feature_flags"),
        ("tags", "0001_metadata_rf_4"),
        ("catalog", "0018_datasource_permission_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={
                "ordering": ("external_name",),
                "verbose_name": "Catalog index",
                "verbose_name_plural": "Catalog indexes",
            },
        ),
        migrations.AlterField(
            model_name="index",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="index",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="user_management.organization",
            ),
        ),
        migrations.AlterField(
            model_name="index",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="_catalog_index_tags_+", to="tags.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="indexpermission",
            name="permission_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="indexpermission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user_management.team",
            ),
        ),
    ]
