# Generated by Django 3.2.7 on 2021-12-06 03:30

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_auto_20210914_1402"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasourcesSyncJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "execute_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs with higher priority will be processed first.",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("args", models.JSONField()),
            ],
            options={
                "db_table": "catalog_datasourcessyncjob",
            },
        ),
    ]
