version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=habari
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: ["wait-for-it", "db:5432", "--", "python", "manage.py", "runserver", "0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ALLOWED_HOSTS="*"
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=habari
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DEBUG=true
      - SECRET_KEY='))dodw9%n)7q86l-q1by4e-2z#vonph50!%ep7_je)_=x0m2v-'
