# Generated by Django 4.2.17 on 2025-01-14 08:21
import uuid

from django.core.validators import validate_slug
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0045_remove_connection"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Connection",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                primary_key=True, default=uuid.uuid4, editable=False
                            ),
                        ),
                        (
                            "workspace",
                            models.ForeignKey(
                                on_delete=models.CASCADE,
                                to="workspaces.Workspace",
                                related_name="connections",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=models.CASCADE, to="user_management.User"
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("slug", models.CharField(max_length=100)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("description", models.TextField(blank=True)),
                        (
                            "connection_type",
                            models.TextField(
                                choices=[
                                    ("S3", "S3 Bucket"),
                                    ("GCS", "GCS Bucket"),
                                    ("POSTGRESQL", "PostgreSQL DB"),
                                    ("CUSTOM", "Custom"),
                                    ("DHIS2", "DHIS2 Instance"),
                                    ("IASO", "IASO Instance"),
                                ],
                                max_length=32,
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="ConnectionField",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                primary_key=True, default=uuid.uuid4, editable=False
                            ),
                        ),
                        (
                            "connection",
                            models.ForeignKey(
                                on_delete=models.CASCADE,
                                to="connections.Connection",
                                related_name="fields",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=models.SET_NULL,
                                to="user_management.User",
                                null=True,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "code",
                            models.CharField(max_length=30, validators=[validate_slug]),
                        ),
                        ("value", models.TextField(blank=True)),
                        ("secret", models.BooleanField(default=False)),
                    ],
                    options={
                        "ordering": ["created_at"],
                        "unique_together": {("connection", "code")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
