# Generated by Django 4.2.17 on 2025-01-14 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0001_add_connection"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="Connection",
            table="connections_connection",
        ),
        migrations.AlterModelTable(
            name="ConnectionField",
            table="connections_connectionfield",
        ),
    ]
