# Generated by Django 3.2 on 2021-04-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
