# Generated by Django 3.2.5 on 2021-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0012_object_s3_etag"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="orphan",
            field=models.BooleanField(default=False),
        ),
    ]
