# Generated by Django 3.2.6 on 2021-08-23 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0019_metadata_rf_1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bucket",
            options={"ordering": ("name",), "verbose_name": "S3 Bucket"},
        ),
        migrations.AlterModelOptions(
            name="object",
            options={"ordering": ("key",), "verbose_name": "S3 Object"},
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="s3_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_dirname",
            new_name="dirname",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_etag",
            new_name="etag",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_key",
            new_name="key",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_last_modified",
            new_name="last_modified",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_size",
            new_name="size",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_storage_class",
            new_name="storage_class",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_type",
            new_name="type",
        ),
    ]
