# Generated by Django 3.2.6 on 2021-08-31 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0020_metadata_rf_3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="object",
            old_name="dirname",
            new_name="parent_key",
        ),
    ]
