# Generated by Django 3.2.7 on 2021-10-18 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0021_rename_dirname_object_parent_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credentials",
            old_name="role_arn",
            new_name="app_role_arn",
        ),
    ]
