# Generated by Django 3.2.7 on 2021-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0022_app_role_arn"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentials",
            name="user_arn",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
