# Generated by Django 4.0 on 2021-12-31 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0025_auto_20211107_1216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="orphan",
        ),
    ]
