# Generated by Django 4.0 on 2022-01-04 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0027_remove_duplicate_objects"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="object",
            unique_together={("bucket", "key")},
        ),
    ]
