# Generated by Django 4.0.4 on 2022-04-27 15:39

from django.db import migrations


def update_bucket_permissions(apps, schema_editor):
    BucketPermission = apps.get_model("connector_s3", "BucketPermission")
    BucketPermission.objects.filter(mode="RW").update(mode="EDITOR")
    BucketPermission.objects.filter(mode="RO").update(mode="VIEWER")


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0029_permissions_next"),
    ]

    operations = [
        migrations.RunPython(update_bucket_permissions, migrations.RunPython.noop),
    ]
