# Generated by Django 3.1.7 on 2021-04-02 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0001_s3_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=200)),
                ("access_key_id", models.CharField(max_length=200)),
                ("secret_access_key", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "S3 Credentials",
                "ordering": ("username",),
            },
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="s3_access_key_id",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="s3_secret_access_key",
        ),
        migrations.AddField(
            model_name="bucket",
            name="credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="connector_s3.credentials",
            ),
        ),
    ]
