# Generated by Django 3.1.7 on 2021-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="size",
            field=models.PositiveBigIntegerField(),
        ),
    ]
