# Generated by Django 3.2.3 on 2021-05-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0003_datasource_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bucket",
            old_name="sync_credentials",
            new_name="api_credentials",
        ),
    ]
