# Generated by Django 3.2 on 2021-04-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        ("connector_s3", "0003_bigger_s3_object_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s3_credentials_set",
                to="user_management.team",
            ),
        ),
    ]
