# Generated by Django 3.2.3 on 2021-05-27 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0004_encrypted_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="last_synced_at",
        ),
    ]
