# Generated by Django 3.1.7 on 2021-04-02 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_s3", "0004_user_credentials"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bucket",
            new_name="S3Bucket",
        ),
        migrations.RenameModel(
            old_name="Credentials",
            new_name="S3Credentials",
        ),
        migrations.RenameModel(
            old_name="Object",
            new_name="S3Object",
        ),
    ]
