# Generated by Django 3.1.7 on 2021-04-06 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_s3", "0005_s3_model_rename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="S3Bucket",
            new_name="Bucket",
        ),
        migrations.RenameModel(
            old_name="S3Credentials",
            new_name="Credentials",
        ),
        migrations.RenameModel(
            old_name="S3Object",
            new_name="Object",
        ),
    ]
