# Generated by Django 3.1.7 on 2021-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0006_models_rename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bucket",
            options={"ordering": ("hexa_name",), "verbose_name": "S3 Bucket"},
        ),
        migrations.AlterModelOptions(
            name="object",
            options={"ordering": ["name"], "verbose_name": "S3 Object"},
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="active_from",
            new_name="hexa_active_from",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="active_to",
            new_name="hexa_active_to",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="countries",
            new_name="hexa_countries",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="description",
            new_name="hexa_description",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="last_synced_at",
            new_name="hexa_last_synced_at",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="locale",
            new_name="hexa_locale",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="s3_name",
            new_name="hexa_name",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="owner",
            new_name="hexa_owner",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="public",
            new_name="hexa_public",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="short_name",
            new_name="hexa_short_name",
        ),
        migrations.RenameField(
            model_name="bucket",
            old_name="url",
            new_name="hexa_url",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="countries",
            new_name="hexa_countries",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="description",
            new_name="hexa_description",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="last_synced_at",
            new_name="hexa_last_synced_at",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="locale",
            new_name="hexa_locale",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="owner",
            new_name="hexa_owner",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="short_name",
            new_name="hexa_short_name",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_last_modified",
            new_name="last_modified",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="s3_name",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="object",
            name="s3_type",
        ),
        migrations.AddField(
            model_name="object",
            name="hexa_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="object",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
