# Generated by Django 3.1.7 on 2021-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0008_fields_rename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credentials",
            options={
                "ordering": ("username",),
                "verbose_name": "S3 Credentials",
                "verbose_name_plural": "S3 Credentials",
            },
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="hexa_url",
        ),
        migrations.AlterField(
            model_name="bucket",
            name="hexa_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
