# Generated by Django 3.1.7 on 2021-04-06 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connector_s3', '0009_fine_tuning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='credentials',
            new_name='sync_credentials',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
