# Generated by Django 3.2.5 on 2021-07-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_tags"),
        ("connector_s3", "0010_s3_default_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="connector_s3.object",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="tags",
            field=models.ManyToManyField(blank=True, to="catalog.Tag"),
        ),
    ]
