# Generated by Django 3.1.7 on 2021-04-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_teams"),
        ("connector_s3", "0011_team_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credentials",
            name="user",
        ),
        migrations.AddField(
            model_name="credentials",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
    ]
