# Generated by Django 3.2.5 on 2021-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_tags"),
        ("connector_s3", "0014_auto_20210727_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="tags",
            field=models.ManyToManyField(blank=True, to="catalog.Tag"),
        ),
    ]
