# Generated by Django 3.2.6 on 2021-08-23 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0018_alter_bucketpermission_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bucket",
            options={"ordering": ("s3_name",), "verbose_name": "S3 Bucket"},
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="active_from",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="active_to",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="description",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="name",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="public",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="bucket",
            name="url",
        ),
        migrations.RemoveField(
            model_name="object",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="object",
            name="description",
        ),
        migrations.RemoveField(
            model_name="object",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="object",
            name="name",
        ),
        migrations.RemoveField(
            model_name="object",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="object",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="object",
            name="tags",
        ),
    ]
