# Generated by Django 3.2.7 on 2021-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0024_auto_20211027_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="auto_sync",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bucketpermission",
            name="mode",
            field=models.IntegerField(
                choices=[(1, "Read Only"), (2, "Read Write")], default=2
            ),
        ),
    ]
