# Generated by Django 4.0 on 2022-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0027_remove_duplicate_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="key",
            field=models.TextField(unique=True),
        ),
    ]
