# Generated by Django 4.0.4 on 2022-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0029_permissions_next"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bucketpermission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team__isnull", False), ("user__isnull", False), _connector="OR"
                ),
                name="bucket_permission_user_or_team_not_null",
            ),
        ),
    ]
