# Generated by Django 4.0.4 on 2022-04-28 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0030_bucket_public"),
        ("connector_s3", "0030_permission_mode_data"),
    ]

    operations = []
