# Generated by Django 4.0.4 on 2022-04-28 08:05

from django.db import migrations


def downgrade_bucket_permissions(apps, schema_editor):
    BucketPermission = apps.get_model("connector_s3", "BucketPermission")
    BucketPermission.objects.filter(mode="VIEWER").update(mode="1")
    BucketPermission.objects.filter(mode="EDITOR").update(mode="2")


def update_bucket_permissions(apps, schema_editor):
    BucketPermission = apps.get_model("connector_s3", "BucketPermission")
    BucketPermission.objects.filter(mode="1").update(mode="VIEWER")
    BucketPermission.objects.filter(mode="2").update(mode="EDITOR")


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0031_merge_0030_bucket_public_0030_permission_mode_data"),
    ]

    operations = [
        migrations.RunPython(
            update_bucket_permissions, reverse_code=downgrade_bucket_permissions
        )
    ]
