# Generated by Django 4.0.6 on 2022-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0032_permission_mode_data_2"),
    ]

    operations = []
