# Generated by Django 4.0.6 on 2022-07-27 14:00

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0001_data_collections"),
        ("connector_s3", "0032_permission_mode_data_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectCollectionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_collections.collection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="object",
            name="collections",
            field=models.ManyToManyField(
                related_name="+",
                through="connector_s3.ObjectCollectionEntry",
                to="data_collections.collection",
            ),
        ),
        migrations.AddField(
            model_name="objectcollectionentry",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connector_s3.object"
            ),
        ),
        migrations.AddConstraint(
            model_name="objectcollectionentry",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("object"),
                django.db.models.expressions.F("collection"),
                name="obj_collection_unique_obj_collection",
            ),
        ),
    ]
