# Generated by Django 4.0.6 on 2022-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0001_data_collections"),
        ("connector_s3", "0032_permission_mode_data_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="collections",
            field=models.ManyToManyField(
                related_name="+", to="data_collections.collection"
            ),
        ),
    ]
