# Generated by Django 4.0.6 on 2022-07-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_s3", "0033_collections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectcollectionitem",
            old_name="object",
            new_name="item",
        ),
    ]
