# Generated by Django 4.1.7 on 2023-05-25 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_s3", "0036_iam_permission_boundary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
