# Generated by Django 3.1.6 on 2021-03-10 09:24

from django.db import migrations, models
import django_countries.fields
import habari.common.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "countries",
                    django_countries.fields.CountryField(
                        blank=True, max_length=746, multiple=True
                    ),
                ),
                (
                    "datasource_type",
                    models.CharField(choices=[("DHIS2", "DHIS2")], max_length=100),
                ),
                ("url", models.URLField(blank=True)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_to", models.DateTimeField(blank=True, null=True)),
                (
                    "public",
                    models.BooleanField(default=False, verbose_name="Public dataset"),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "text_search_config",
                    habari.common.models.PostgresTextSearchConfigField(
                        choices=[
                            ("simple", "simple"),
                            ("french", "french"),
                            ("english", "english"),
                        ],
                        default="simple",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
