# Generated by Django 3.1.5 on 2021-01-05 13:13

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("CORPORATE", "Corporate"),
                            ("ACADEMIC", "Academic"),
                            ("GOVERNMENT", "Government"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("DHIS2", "DHIS2"),
                            ("IASO", "Iaso"),
                            ("FILES", "Files"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_to", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.organization",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
