# Generated by Django 3.1.6 on 2021-02-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="areas",
            field=models.ManyToManyField(blank=True, to="catalog.Area"),
        ),
        migrations.AddField(
            model_name="datasource",
            name="themes",
            field=models.ManyToManyField(blank=True, to="catalog.Theme"),
        ),
    ]
