# Generated by Django 3.1.6 on 2021-03-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourceindex",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="contentindex",
            name="datasource_index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.datasourceindex",
            ),
        ),
    ]
