# Generated by Django 3.1.6 on 2021-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogindex",
            name="content_summary",
            field=models.TextField(blank=True),
        ),
    ]
