# Generated by Django 3.1.5 on 2021-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_data_items_and_finetuning"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource", name="url", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization", name="url", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="dhis2dataelement",
            name="dhis2_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dhis2indicator",
            name="dhis2_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
