# Generated by Django 3.1.6 on 2021-03-04 13:33

from django.db import migrations
import habari.common.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_area_themes_many2many"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="text_search_config",
            field=habari.common.models.PostgresTextSearchConfigField(
                choices=[
                    ("simple", "simple"),
                    ("french", "french"),
                    ("english", "english"),
                ],
                default="simple",
                max_length=100,
            ),
        ),
    ]
