# Generated by Django 3.1.5 on 2021-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_public_datasets"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
