# Generated by Django 3.1.5 on 2021-01-19 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_source_synced_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dhis2DataSourceSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_url", models.URLField()),
                ("api_username", models.CharField(max_length=200)),
                ("api_password", models.CharField(max_length=200)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
