# Generated by Django 3.1.5 on 2021-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_unique_dhis2_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contact_info",
            field=models.TextField(blank=True),
        ),
    ]
