# Generated by Django 3.1.5 on 2021-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_org_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dhis2dataelement", options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dhis2indicator", options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="datasource", old_name="source_type", new_name="datasource_type",
        ),
        migrations.AlterField(
            model_name="dhis2dataelement",
            name="dhis2_value_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("LONG_TEXT", "Long text"),
                    ("LETTER", "Letter"),
                    ("PHONE_NUMBER", "Phone number"),
                    ("EMAIL", "Email"),
                    ("YES_NO", "Yes/No"),
                    ("YES_ONLY", "Yes Only"),
                    ("DATE", "Date"),
                    ("DATE_AND_TIME", "Date & Time"),
                    ("TIME", "Time"),
                    ("NUMBER", "Number"),
                    ("UNIT_INTERVAL", "Unit interval"),
                    ("PERCENTAGE", "Percentage"),
                    ("INTEGER", "Integer"),
                    ("POSITIVE_INTEGER", "Positive Integer"),
                    ("INTEGER_POSITIVE", "Positive Integer"),
                    ("NEGATIVE_INTEGER", "Negative Integer"),
                    ("INTEGER_NEGATIVE", "Negative Integer"),
                    ("POSITIVE_OR_ZERO_INTEGER", "Positive or Zero Integer"),
                    ("INTEGER_ZERO_OR_POSITIVE", "Positive or Zero Integer"),
                    ("TRACKER_ASSOCIATE", "Tracker Associate"),
                    ("USERNAME", "Username"),
                    ("COORDINATE", "Coordinate"),
                    ("ORGANISATION_UNIT", "Organisation Unit"),
                    ("AGE", "Age"),
                    ("URL", "URL"),
                    ("FILE", "File"),
                    ("IMAGE", "Image"),
                ],
                max_length=100,
            ),
        ),
    ]
