# Generated by Django 3.1.6 on 2021-02-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_source_type_rename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dhis2connection",
            old_name="source",
            new_name="datasource",
        ),
        migrations.RenameField(
            model_name="dhis2dataelement",
            old_name="source",
            new_name="datasource",
        ),
        migrations.RenameField(
            model_name="dhis2indicator",
            old_name="source",
            new_name="datasource",
        ),
    ]
