# Generated by Django 4.2.17 on 2024-12-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinetemplate",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
