# Generated by Django 4.2.17 on 2025-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0004_alter_pipelinetemplate_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplateversion",
            name="changelog",
            field=models.TextField(blank=True, null=True),
        ),
    ]
