# Generated by Django 4.2.17 on 2025-01-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0055_pipelineversion_source_template_version"),
        ("pipeline_templates", "0004_alter_pipelinetemplate_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinetemplate",
            name="source_pipeline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template",
                to="pipelines.pipeline",
            ),
        ),
    ]
