# Generated by Django 4.2.17 on 2025-01-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0055_pipelineversion_source_template_version"),
        ("pipeline_templates", "0005_alter_pipelinetemplate_source_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinetemplateversion",
            name="source_pipeline_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_version",
                to="pipelines.pipelineversion",
            ),
        ),
    ]
