# Generated by Django 4.2.17 on 2025-01-22 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0005_pipelinetemplateversion_changelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinetemplate",
            name="config",
        ),
    ]
