# Generated by Django 4.2.17 on 2025-02-10 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipelines", "0056_pipelinerun_pipelines_p_access__4788e4_idx"),
        ("pipeline_templates", "0006_remove_pipelinetemplate_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplateversion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinetemplateversion",
            name="source_pipeline_version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_version",
                to="pipelines.pipelineversion",
            ),
        ),
    ]
