# Generated by Django 4.2.17 on 2025-02-03 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipeline_templates",
            "0006_alter_pipelinetemplateversion_source_pipeline_version",
        ),
        ("pipeline_templates", "0006_remove_pipelinetemplate_config"),
    ]

    operations = []
