# Generated by Django 4.0.2 on 2022-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0005_role_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesetrole",
            name="code",
            field=models.CharField(default="nocode", max_length=50),
            preserve_default=False,
        ),
    ]
