# Generated by Django 4.0.2 on 2022-02-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0009_analysis_finetuning_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilityanalysis",
            name="extent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_accessmod.fileset",
            ),
        ),
    ]
