# Generated by Django 4.0.2 on 2022-02-28 18:03

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0015_am_extent_on_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="uri",
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name="fileset",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("project"),
                name="fileset_unique_name_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("owner"),
                name="project_unique_name_owner",
            ),
        ),
    ]
