# Generated by Django 4.0.4 on 2022-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0024_fileset_status_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Project description"
            ),
        ),
    ]
