# Generated by Django 4.0.4 on 2022-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0028_project_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileset",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO ACQUIRE", "To Acquire"),
                    ("PENDING", "Pending"),
                    ("VALIDATING", "Validating"),
                    ("VALID", "Valid"),
                    ("INVALID", "Invalid"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
