# Generated by Django 4.0.4 on 2022-05-04 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_accessmod",
            "0030_accessibilityanalysis_stack_alter_filesetrole_code",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessibilityanalysis",
            name="catchment_areas",
        ),
    ]
