# Generated by Django 4.0.4 on 2022-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0033_accessibilityanalysis_stack_priorities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessibilityanalysis", name="moving_speeds"
        ),
        migrations.AddField(
            model_name="accessibilityanalysis",
            name="moving_speeds",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
