# Generated by Django 4.0.4 on 2022-05-12 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0029_alter_fileset_status"),
        ("connector_accessmod", "0036_alter_filesetrole_code"),
    ]

    operations = []
