# Generated by Django 4.0.4 on 2022-05-24 05:17

from django.db import migrations, models


def stack_priorities_to_list(apps, schema_editor):
    AccessibilityAnalysis = apps.get_model(
        "connector_accessmod", "AccessibilityAnalysis"
    )
    AccessibilityAnalysis.objects.update(stack_priorities=list())


def stack_priorities_to_dict(apps, schema_editor):
    AccessibilityAnalysis = apps.get_model(
        "connector_accessmod", "AccessibilityAnalysis"
    )
    AccessibilityAnalysis.objects.filter(stack_priorities=[]).update(
        stack_priorities={}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0045_am_blank_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityanalysis",
            name="stack_priorities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(
            stack_priorities_to_list, reverse_code=stack_priorities_to_dict
        ),
    ]
