# Generated by Django 4.0.4 on 2022-06-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0047_zonalstatisticsanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonalstatisticsanalysis",
            name="zonal_statistics_geo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_accessmod.fileset",
            ),
        ),
        migrations.AddField(
            model_name="zonalstatisticsanalysis",
            name="zonal_statistics_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_accessmod.fileset",
            ),
        ),
    ]
