# Generated by Django 4.0.4 on 2022-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_accessmod",
            "0048_zonalstatisticsanalysis_zonal_statistics_geo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fileset",
            name="vizualisation_uri",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
