# Generated by Django 4.0.4 on 2022-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_accessmod",
            "0050_rename_vizualisation_uri_fileset_visualization_uri",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityanalysis",
            name="algorithm",
            field=models.CharField(
                choices=[("ANISOTROPIC", "Anisotropic"), ("ISOTROPIC", "Isotropic")],
                default="ISOTROPIC",
                max_length=50,
            ),
        ),
    ]
