# Generated by Django 4.0.4 on 2022-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0052_am_zonal_stats_vname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileset",
            name="visualization_uri",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
