# Generated by Django 4.0.6 on 2022-07-29 05:43

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0055_alter_accessrequest_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254),
        ),
    ]
