# Generated by Django 4.2.6 on 2023-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0057_remove_project_auto_sync_and_more"),
        ("core", "0009_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="email",
            field=models.EmailField(db_collation="case_insensitive", max_length=254),
        ),
    ]
