# Generated by Django 5.1.5 on 2025-02-17 20:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupersetInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("admin_username", models.CharField(max_length=255)),
                ("admin_password", hexa.core.models.cryptography.EncryptedTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupersetDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "superset_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superset.supersetinstance",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="superset_su_externa_02a69a_idx"
                    )
                ],
                "unique_together": {("external_id", "superset_instance")},
            },
        ),
    ]
