# Generated by Django 5.1.5 on 2025-12-01 00:00

import django.db.models.deletion
from django.db import migrations, models


def set_blsq_organization(apps, schema_editor):
    """Set all existing SupersetInstance records to BLSQ organization."""
    SupersetInstance = apps.get_model("superset", "SupersetInstance")
    Organization = apps.get_model("user_management", "Organization")

    # Get BLSQ organization
    try:
        blsq_org = Organization.objects.get(short_name="BLSQ")
    except Organization.DoesNotExist:
        # If BLSQ doesn't exist, skip this migration
        # In production, BLSQ should exist
        return

    SupersetInstance.objects.filter(organization__isnull=True).update(
        organization=blsq_org
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "superset",
            "0002_rename_admin_password_supersetinstance_api_password_and_more",
        ),
        ("user_management", "0020_user_analytics_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="supersetinstance",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superset_instances",
                to="user_management.organization",
            ),
        ),
        migrations.RunPython(set_blsq_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="supersetinstance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superset_instances",
                to="user_management.organization",
            ),
        ),
    ]
