# Generated by Django 5.2.7 on 2026-02-13 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("superset", "0003_supersetinstance_organization"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supersetdashboard",
            unique_together=set(),
        ),
    ]
