# Generated by Django 3.2.6 on 2021-08-27 09:25
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_abstract_index"),
    ]

    operations = [CreateExtension("ltree")]
