# Generated by Django 5.2.14 on 2026-06-22 20:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_case_insensitive_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.TextField()),
                ("recipients", models.JSONField(default=list)),
                ("text_body", models.TextField()),
                ("html_body", models.TextField(blank=True, default="")),
                ("attachments", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_failed_email",
                "ordering": ("-created_at",),
            },
        ),
    ]
