# Generated by Django 4.0.4 on 2022-07-27 11:51

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

import hexa.catalog.models
import hexa.core.models.cryptography


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0011_unique_fine_tuning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IASOAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_sync", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("api_url", models.URLField()),
                ("username", hexa.core.models.cryptography.EncryptedTextField()),
                ("password", hexa.core.models.cryptography.EncryptedTextField()),
            ],
            options={
                "verbose_name": "IASO Account",
                "verbose_name_plural": "IASO Account",
                "ordering": ("api_url",),
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IASOPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="EDITOR",
                        max_length=200,
                    ),
                ),
                (
                    "iaso_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_iaso.iasoaccount",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IASO Permission",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IASOForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("iaso_id", models.IntegerField(editable=False, unique=True)),
                ("name", models.TextField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("form_id", models.CharField(default="", max_length=50)),
                ("version_id", models.CharField(max_length=20, null=True)),
                ("file_uri", models.TextField(null=True)),
                ("org_unit_types", models.JSONField(blank=True, default=dict)),
                ("projects", models.JSONField(blank=True, default=dict)),
                (
                    "iaso_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_iaso.iasoaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "IASO Form",
                "ordering": ("name",),
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="iasopermission",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("team"),
                django.db.models.expressions.F("iaso_account"),
                name="iaso_unique_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="iasopermission",
            constraint=models.CheckConstraint(
                check=models.Q(("team__isnull", False)),
                name="iaso_permission_team_not_null",
            ),
        ),
    ]
