# Generated by Django 4.0.4 on 2022-08-03 10:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hexa.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_iaso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IASOOrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("iaso_id", models.IntegerField(editable=False, unique=True)),
                ("name", models.TextField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("org_unit_type_id", models.IntegerField()),
                ("org_unit_type_name", models.CharField(default="", max_length=50)),
                ("iaso_parent_id", models.IntegerField(null=True)),
                (
                    "iaso_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_iaso.iasoaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "IASO OrgUnit",
                "ordering": ("name",),
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IASOApiToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(default="", max_length=250)),
                (
                    "iaso_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_iaso.iasoaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IASO API Token",
            },
        ),
        migrations.AddConstraint(
            model_name="iasoapitoken",
            constraint=models.UniqueConstraint(
                fields=("iaso_account", "user"), name="user-iaso"
            ),
        ),
    ]
