# Generated by Django 4.0.4 on 2022-09-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "connector_iaso",
            "0002_rename_iasoform_form_rename_iasoaccount_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_id",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
