# Generated by Django 4.1.7 on 2023-08-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_iaso", "0003_alter_form_form_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apitoken",
            name="iaso_account",
        ),
        migrations.RemoveField(
            model_name="apitoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="form",
            name="iaso_account",
        ),
        migrations.RemoveField(
            model_name="iasopermission",
            name="iaso_account",
        ),
        migrations.RemoveField(
            model_name="iasopermission",
            name="team",
        ),
        migrations.RemoveField(
            model_name="iasopermission",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orgunit",
            name="iaso_account",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="ApiToken",
        ),
        migrations.DeleteModel(
            name="Form",
        ),
        migrations.DeleteModel(
            name="IASOPermission",
        ),
        migrations.DeleteModel(
            name="OrgUnit",
        ),
    ]
