# Generated by Django 4.0.4 on 2022-04-21 12:22

import uuid

from django.db import migrations, models

import hexa.catalog.models
import hexa.core.models.cryptography


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_sync", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "GCS Bucket",
                "ordering": ("name",),
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_account", models.CharField(max_length=30)),
                ("project_id", models.CharField(max_length=30)),
                ("client_id", models.CharField(max_length=30)),
                ("client_email", models.CharField(max_length=100)),
                ("client_x509_cert_url", models.CharField(max_length=150)),
                (
                    "auth_uri",
                    models.CharField(
                        default="https://accounts.google.com/o/oauth2/auth",
                        max_length=100,
                    ),
                ),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=100
                    ),
                ),
                (
                    "auth_provider_x509_cert_url",
                    models.CharField(
                        default="https://www.googleapis.com/oauth2/v1/certs",
                        max_length=100,
                    ),
                ),
                (
                    "private_key_id",
                    hexa.core.models.cryptography.EncryptedTextField(max_length=50),
                ),
                ("private_key", hexa.core.models.cryptography.EncryptedTextField()),
            ],
            options={
                "verbose_name": "GCS Credentials",
                "verbose_name_plural": "GCS Credentials",
                "ordering": ("service_account",),
            },
        ),
    ]
