# Generated by Django 4.0.4 on 2022-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_gcs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
