# Generated by Django 4.0.4 on 2022-05-23 13:58

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hexa.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_gcs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.TextField()),
                ("parent_key", models.TextField()),
                ("size", models.PositiveBigIntegerField()),
                ("type", models.CharField(max_length=200)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_gcs.bucket",
                    ),
                ),
            ],
            options={
                "verbose_name": "GCS Object",
                "ordering": ("key",),
                "unique_together": {("bucket", "key")},
            },
            bases=(hexa.catalog.models.IndexableMixin, models.Model),
        ),
    ]
