# Generated by Django 4.0.4 on 2022-05-10 07:20

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0011_unique_fine_tuning"),
        ("connector_gcs", "0002_bucket_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="GCSBucketPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="EDITOR",
                        max_length=200,
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_gcs.bucket",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="gcsbucketpermission",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("team"),
                django.db.models.expressions.F("bucket"),
                condition=models.Q(("team__isnull", False)),
                name="gcs_bucket_unique_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcsbucketpermission",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("user"),
                django.db.models.expressions.F("bucket"),
                condition=models.Q(("user__isnull", False)),
                name="gcs_bucket_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcsbucketpermission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team__isnull", False), ("user__isnull", False), _connector="OR"
                ),
                name="gcs_bucket_permission_user_or_team_not_null",
            ),
        ),
    ]
