# Generated by Django 4.1.7 on 2023-05-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_gcs", "0002_object"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
