# Generated by Django 4.1.7 on 2023-06-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_gcs", "0003_delete_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gcsbucketpermission",
            name="bucket",
        ),
        migrations.RemoveField(
            model_name="gcsbucketpermission",
            name="team",
        ),
        migrations.RemoveField(
            model_name="gcsbucketpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="object",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="object",
            name="bucket",
        ),
        migrations.DeleteModel(
            name="Bucket",
        ),
        migrations.DeleteModel(
            name="GCSBucketPermission",
        ),
        migrations.DeleteModel(
            name="Object",
        ),
    ]
