# Generated by Django 4.0.4 on 2022-05-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_gcs", "0003_gcsbucketpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gcsbucketpermission",
            options={"verbose_name": "Bucket Permission"},
        ),
    ]
