# Generated by Django 4.0.1 on 2022-01-25 18:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0002_filesets"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mime_type", models.CharField(max_length=50)),
                ("uri", models.TextField()),
                (
                    "fileset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connector_accessmod.fileset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
