# Generated by Django 4.0.2 on 2022-02-17 15:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_accessmod", "0007_alter_filesetrole_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileset",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="connector_accessmod.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeographicCoverageAnalysis",
            fields=[
                (
                    "analysis_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connector_accessmod.analysis",
                    ),
                ),
                ("anisotropic", models.BooleanField(null=True)),
                ("max_travel_time", models.IntegerField(null=True)),
                ("hf_processing_order", models.CharField(max_length=100)),
                (
                    "catchment_areas",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "dem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "friction_surface",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "geographic_coverage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "health_facilities",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("connector_accessmod.analysis",),
        ),
        migrations.CreateModel(
            name="AccessibilityAnalysis",
            fields=[
                (
                    "analysis_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connector_accessmod.analysis",
                    ),
                ),
                ("extent", models.JSONField(null=True)),
                ("anisotropic", models.BooleanField(null=True)),
                ("max_travel_time", models.IntegerField(null=True)),
                (
                    "barrier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "dem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "friction_surface",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "health_facilities",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "land_cover",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "moving_speeds",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "slope",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "transport_network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "travel_times",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "water",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("connector_accessmod.analysis",),
        ),
    ]
