# Generated by Django 4.0.2 on 2022-02-17 09:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_accessmod", "0007_alter_filesetrole_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ACCESSIBILITY", "Accessibility"),
                            ("GEOGRAPHIC_COVERAGE", "Geographic Coverage"),
                            ("ZONAL_STATISTICS", "Zonal Statistics"),
                            ("REFERRAL", "Referral"),
                            ("SCALING_UP", "Scaling Up"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccessibilityAnalysis",
            fields=[
                (
                    "analysis_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connector_accessmod.analysis",
                    ),
                ),
                ("extent", models.JSONField()),
                ("anisotropic", models.BooleanField()),
                ("max_travel_time", models.BooleanField()),
                (
                    "barrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "dem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "friction_surface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "health_facilities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "land_cover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "moving_speeds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "slope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "transport_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "travel_times",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
                (
                    "water",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connector_accessmod.fileset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("connector_accessmod.analysis",),
        ),
    ]
