# Generated by Django 4.0.2 on 2022-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_accessmod", "0010_analysis_finetuning_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crs",
            field=models.PositiveIntegerField(default=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY", "Ready"),
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
