# Generated by Django 4.0.2 on 2022-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0011_crs_status_coverage_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="mime_type",
            field=models.CharField(max_length=255),
        ),
    ]
