# Generated by Django 4.0.2 on 2022-02-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
        ("connector_accessmod", "0013_alter_filesetrole_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="dag_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="connector_airflow.dagrun",
            ),
        ),
    ]
