# Generated by Django 4.0.2 on 2022-02-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
        ("connector_accessmod", "0013_am_accessibility_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="dag_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="connector_airflow.dagrun",
            ),
        ),
        migrations.AlterField(
            model_name="filesetrole",
            name="code",
            field=models.CharField(
                choices=[
                    ("BARRIER", "Barrier"),
                    ("CATCHMENT_AREAS", "Catchment Areas"),
                    ("COVERAGE", "Coverage"),
                    ("DEM", "Dem"),
                    ("FRICTION_SURFACE", "Friction Surface"),
                    ("GEOMETRY", "Geometry"),
                    ("HEALTH_FACILITIES", "Health Facilities"),
                    ("LAND_COVER", "Land Cover"),
                    ("MOVING_SPEEDS", "Moving Speeds"),
                    ("POPULATION", "Population"),
                    ("SLOPE", "Slope"),
                    ("TRANSPORT_NETWORK", "Transport Network"),
                    ("TRAVEL_TIMES", "Travel Times"),
                    ("WATER", "Water"),
                ],
                max_length=50,
            ),
        ),
    ]
