# Generated by Django 4.0.2 on 2022-03-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
        ("connector_accessmod", "0018_analysis_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="dag_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_airflow.dagrun",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="connector_accessmod.project",
            ),
        ),
    ]
