# Generated by Django 4.0.2 on 2022-03-07 17:17

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0025_am_webhook_token"),
        ("connector_accessmod", "0018_analysis_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="dag_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_airflow.dagrun",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="connector_accessmod.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysis",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("project"),
                name="analysis_unique_name_project",
            ),
        ),
    ]
