# Generated by Django 4.0.3 on 2022-04-05 15:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_accessmod", "0020_am_teams"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="project_unique_name_owner",
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="fileset",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="author",
        ),
        migrations.AddField(
            model_name="projectpermission",
            name="mode",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("GUEST", "Guest")],
                default="OWNER",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("author"),
                name="project_unique_name_owner",
            ),
        ),
    ]
