# Generated by Django 4.0.4 on 2022-04-13 04:52

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0009_user_management_to_identity_1"),
        ("connector_accessmod", "0020_am_teams"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analysispermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="analysispermission",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="analysispermission",
            name="team",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project_unique_name_owner",
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="fileset",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="author",
        ),
        migrations.AddField(
            model_name="projectpermission",
            name="mode",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="EDITOR",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="projectpermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectpermission",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("author"),
                name="project_unique_name_owner",
            ),
        ),
        migrations.DeleteModel(
            name="AnalysisPermission",
        ),
    ]
