# Generated by Django 4.0.3 on 2022-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_accessmod", "0022_permissions_user_or_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpermission",
            name="mode",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("EDITOR", "Editor")],
                default="EDITOR",
                max_length=200,
            ),
        ),
        migrations.DeleteModel(
            name="AnalysisPermission",
        ),
    ]
