# Generated by Django 4.0.4 on 2022-04-13 10:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0022_create_author_permissions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="project_unique_name_owner",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("name"),
                django.db.models.expressions.F("author"),
                name="project_unique_name_author",
            ),
        ),
    ]
