# Generated by Django 4.0.4 on 2022-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0025_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Project description"
            ),
            preserve_default=False,
        ),
    ]
