# Generated by Django 4.0.4 on 2022-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_accessmod",
            "0032_remove_accessibilityanalysis_priority_land_cover_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilityanalysis",
            name="stack_priorities",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
