# Generated by Django 4.0.4 on 2022-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0034_alter_accessibilityanalysis_moving_speeds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessibilityanalysis",
            name="max_slope",
        ),
        migrations.RemoveField(
            model_name="accessibilityanalysis",
            name="slope",
        ),
    ]
