# Generated by Django 4.0.4 on 2022-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0044_am_roles_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityanalysis",
            name="friction_surface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_accessmod.fileset",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilityanalysis",
            name="travel_times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="connector_accessmod.fileset",
            ),
        ),
    ]
