# Generated by Django 4.0.4 on 2022-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "connector_accessmod",
            "0048_zonalstatisticsanalysis_zonal_statistics_geo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityanalysis",
            name="algorithm",
            field=models.CharField(
                choices=[("ANISOTROPIC", "Anisotropic"), ("ISOTROPIC", "Isotropic")],
                default="ISOTROPIC",
                max_length=50,
            ),
        ),
    ]
