# Generated by Django 4.0.4 on 2022-06-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_accessmod", "0049_alter_accessibilityanalysis_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileset",
            name="vizualisation_uri",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
