# Generated by Django 4.0.4 on 2022-06-27 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_accessmod", "0049_fileset_vizualisation_uri"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileset",
            old_name="vizualisation_uri",
            new_name="visualization_uri",
        ),
    ]
