# Generated by Django 4.0.6 on 2022-07-22 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_accessmod", "0054_am_signup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminProfile",
            new_name="AccessmodProfile",
        ),
    ]
