"""
Django settings for hexa.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import re
from pathlib import Path
from urllib.parse import urlparse

from corsheaders.defaults import default_headers
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: keep the encryption key used in production secret!
ENCRYPTION_KEY = os.environ.get("ENCRYPTION_KEY")

# X Frame Options
X_FRAME_OPTIONS = "DENY"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false") == "true"

# Trust the X_FORWARDED_PROTO header from the proxy or load balancer so Django is aware it is accessed by https
if os.environ.get("TRUST_FORWARDED_PROTO", "false") == "true":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

TLS = os.environ.get("TLS", "false") == "true"
SCHEME = "https" if TLS else "http"

SECURE_REDIRECT_EXEMPT = [r"^ready$"]
if TLS or os.environ.get("TRUST_FORWARDED_PROTO", "false") == "true":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = TLS
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

BASE_HOSTNAME = os.environ.get("BASE_HOSTNAME", "localhost")
BASE_PORT = os.environ.get("BASE_PORT", 8000)

# Needed so that external component know how to hit us back
# Do not add a trailing slash
BASE_URL = os.environ.get("BASE_URL", f"{SCHEME}://{BASE_HOSTNAME}:{BASE_PORT}")
INTERNAL_BASE_URL = os.environ.get("INTERNAL_BASE_URL", BASE_URL)

ALLOWED_HOSTS = (
    os.environ.get("ADDITIONAL_ALLOWED_HOSTS").split(",")
    if "ADDITIONAL_ALLOWED_HOSTS" in os.environ
    else []
)

CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []
if "PROXY_HOSTNAME_AND_PORT" in os.environ:
    SCHEME = (
        "https"
        if os.environ.get("TRUST_FORWARDED_PROTO", "false") == "true"
        else SCHEME
    )
    PROXY_URL = f"{SCHEME}://{os.environ.get('PROXY_HOSTNAME_AND_PORT')}"
    BASE_URL = PROXY_URL
    NEW_FRONTEND_DOMAIN = os.environ.get(
        "NEW_FRONTEND_DOMAIN", os.environ.get("PROXY_HOSTNAME_AND_PORT")
    )
    if not re.match(r"^https?://", NEW_FRONTEND_DOMAIN, re.IGNORECASE):
        # Add the scheme if it is missing
        NEW_FRONTEND_DOMAIN = f"{SCHEME}://{NEW_FRONTEND_DOMAIN}"
    NOTEBOOKS_URL = os.environ.get("NOTEBOOKS_URL", PROXY_URL)
    CORS_ALLOWED_ORIGINS = [PROXY_URL]
    CSRF_TRUSTED_ORIGINS = [PROXY_URL]
    ALLOWED_HOSTS += [urlparse(NEW_FRONTEND_DOMAIN).netloc.split(":")[0]]
else:
    NEW_FRONTEND_DOMAIN = os.environ.get(
        "NEW_FRONTEND_DOMAIN",
        f"{BASE_HOSTNAME}:{os.environ.get('FRONTEND_PORT', 3000)}",
    )
    NOTEBOOKS_URL = os.environ.get(
        "NOTEBOOKS_URL",
        f"{SCHEME}://{BASE_HOSTNAME}:{os.environ.get('JUPYTERHUB_PORT', 8001)}",
    )
    if not re.match(r"^https?://", NEW_FRONTEND_DOMAIN, re.IGNORECASE):
        # Add the scheme if it is missing
        NEW_FRONTEND_DOMAIN = f"{SCHEME}://{NEW_FRONTEND_DOMAIN}"
    CORS_ALLOWED_ORIGINS = [NEW_FRONTEND_DOMAIN]
    CSRF_TRUSTED_ORIGINS = [NEW_FRONTEND_DOMAIN]
    ALLOWED_HOSTS += [BASE_HOSTNAME]

# CORS (For GraphQL)
# https://github.com/adamchainz/django-cors-headers
if "CORS_ALLOWED_ORIGINS" in os.environ:
    CORS_ALLOWED_ORIGINS += os.environ.get("CORS_ALLOWED_ORIGINS").split(",")

CORS_URLS_REGEX = r"^/graphql/(\w+/)?|^/analytics/track/|^/files/[\w/]+/?$"
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "sentry-trace",
]

# CSRF
if "CSRF_TRUSTED_ORIGINS" in os.environ:
    CSRF_TRUSTED_ORIGINS += os.environ.get("CSRF_TRUSTED_ORIGINS").split(",")

SESSION_COOKIE_DOMAIN = os.environ.get("SESSION_COOKIE_DOMAIN", None)
CSRF_COOKIE_DOMAIN = os.environ.get("CSRF_COOKIE_DOMAIN", None)
SECURE_HSTS_SECONDS = os.environ.get(
    "SECURE_HSTS_SECONDS", 60 * 60
)  # TODO: increase to one year if ok

# Application definition
INSTALLED_APPS = [
    # http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.gis",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_countries",
    "django_ltree",
    "ariadne_django",
    "dpq",
    "hexa.user_management",
    "hexa.analytics",
    "hexa.core",
    "hexa.catalog",
    "hexa.countries",
    "hexa.notebooks",
    "hexa.pipelines",
    "hexa.pipeline_templates",
    "hexa.comments",
    "hexa.tags",
    "hexa.ui",
    "hexa.plugins.connector_dhis2",
    "hexa.plugins.connector_s3",
    "hexa.plugins.connector_airflow",
    "hexa.plugins.connector_postgresql",
    "hexa.plugins.connector_accessmod",
    "hexa.workspaces",
    "hexa.databases",
    "hexa.metadata",
    "hexa.files",
    "hexa.datasets",
    "hexa.superset",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_email",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "hexa.core.middlewares.set_remote_addr_from_forwarded_for",
    "hexa.user_management.middlewares.TwoFactorMiddleware",
    "hexa.user_management.middlewares.UserLanguageMiddleware",
    "hexa.plugins.connector_airflow.middlewares.dag_run_authentication_middleware",
    "hexa.pipelines.middlewares.pipeline_run_authentication_middleware",
    "hexa.workspaces.middlewares.workspace_token_authentication_middleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "hexa.user_management.middlewares.login_required_middleware",
    "hexa.analytics.middlewares.set_analytics_middleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "hexa" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "hexa.core.context_processors.global_variables",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.environ.get("DATABASE_PORT"),
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
    }
}

# Auth settings
LOGIN_URL = "core:login"
LOGOUT_REDIRECT_URL = "core:login"

# Custom user model
# https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "user_management.User"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends
# https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#authentication-backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "hexa.user_management.backends.PermissionsBackend",
]

# by default users need to login every 2 weeks -> update to 1 year
SESSION_COOKIE_AGE = 365 * 24 * 3600

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_COOKIE_NAME = "hexa_language"
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
]
LOCALE_PATHS = [BASE_DIR / "hexa" / "locale"]
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "hexa" / "static"]
MEDIA_ROOT = BASE_DIR / "static" / "uploads"

# Whitenoise
# http://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if os.environ.get("DEBUG_TOOLBAR", "false") == "true":
    INSTALLED_APPS.append("debug_toolbar")  # noqa: F405
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")  # noqa: F405
    # Django Debug Toolbar specifically ask for INTERNAL_IPS to be set
    INTERNAL_IPS = ["127.0.0.1"]

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: request.user.is_staff,
    }

# Notebooks component
NOTEBOOKS_HUB_URL = os.environ.get("NOTEBOOKS_HUB_URL", "http://jupyterhub:8000/hub")
HUB_API_TOKEN = os.environ.get("HUB_API_TOKEN", "")

GRAPHQL_DEFAULT_PAGE_SIZE = 10
GRAPHQL_MAX_PAGE_SIZE = 10_000

# Logging
if os.environ.get("DEBUG_LOGGING", "false") == "true":
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
        },
    }

# Disabling the check on the size of the request body when using the file system storage backend
# This is needed to allow the upload of large files when they are not stored by an external storage backend
if os.environ.get("DISABLE_UPLOAD_MAX_SIZE_CHECK", "false") == "true":
    DATA_UPLOAD_MAX_MEMORY_SIZE = None

# Email settings
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS") == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL") == "true"
EMAIL_USE_LOCALTIME = os.environ.get("EMAIL_USE_LOCALTIME") == "true"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "OpenHEXA <hexatron@notifications.openhexa.org>"
)

if all([EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD]):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Sync settings: sync datasource with a worker (good for scaling) or in the web serv (good for dev)
EXTERNAL_ASYNC_REFRESH = os.environ.get("EXTERNAL_ASYNC_REFRESH") == "true"

## Specific settings for airflow plugins

# number of second of airflow dag reloading setting
AIRFLOW_SYNC_WAIT = 61
GCS_TOKEN_LIFETIME = os.environ.get("GCS_TOKEN_LIFETIME", 3600)

# Pipeline settings
PIPELINE_SCHEDULER_SPAWNER = os.environ.get("PIPELINE_SCHEDULER_SPAWNER", "docker")
DEFAULT_WORKSPACE_IMAGE = os.environ.get(
    "DEFAULT_WORKSPACE_IMAGE", "blsq/openhexa-base-environment:latest"
)
PIPELINE_DEFAULT_CONTAINER_CPU_LIMIT = os.environ.get(
    "PIPELINE_DEFAULT_CONTAINER_CPU_LIMIT", "2"
)
PIPELINE_DEFAULT_CONTAINER_MEMORY_LIMIT = os.environ.get(
    "PIPELINE_DEFAULT_CONTAINER_MEMORY_LIMIT", "4G"
)
PIPELINE_DEFAULT_CONTAINER_CPU_REQUEST = os.environ.get(
    "PIPELINE_DEFAULT_CONTAINER_CPU_REQUEST", "0.05"
)
PIPELINE_DEFAULT_CONTAINER_MEMORY_REQUEST = os.environ.get(
    "PIPELINE_DEFAULT_CONTAINER_MEMORY_REQUEST", "100M"
)
PIPELINE_RUN_DEFAULT_TIMEOUT = os.environ.get("PIPELINE_RUN_DEFAULT_TIMEOUT", 14400)
PIPELINE_RUN_MAX_TIMEOUT = os.environ.get("PIPELINE_RUN_MAX_TIMEOUT", 43200)

# Two Factor Authentication
OTP_EMAIL_BODY_TEMPLATE_PATH = "user_management/token.txt"
OTP_EMAIL_SENDER = DEFAULT_FROM_EMAIL
OTP_EMAIL_SUBJECT = "OpenHEXA Verification Token"

# Workspace Database settings
WORKSPACES_DATABASE_ROLE = os.environ.get("WORKSPACES_DATABASE_ROLE")
WORKSPACES_DATABASE_PASSWORD = os.environ.get("WORKSPACES_DATABASE_PASSWORD")
WORKSPACES_DATABASE_HOST = os.environ.get("WORKSPACES_DATABASE_HOST")
WORKSPACES_DATABASE_PORT = os.environ.get("WORKSPACES_DATABASE_PORT")
WORKSPACES_DATABASE_DEFAULT_DB = os.environ.get("WORKSPACES_DATABASE_DEFAULT_DB")
WORKSPACES_DATABASE_PROXY_HOST = os.environ.get("WORKSPACES_DATABASE_PROXY_HOST")

# Datasets config
WORKSPACE_DATASETS_BUCKET = os.environ.get("WORKSPACE_DATASETS_BUCKET", "hexa-datasets")
WORKSPACE_DATASETS_FILE_SNAPSHOT_SIZE = int(
    os.environ.get("WORKSPACE_DATASETS_FILE_SNAPSHOT_SIZE", 50)
)
# Filesystem configuration
WORKSPACE_STORAGE_LOCATION = os.environ.get("WORKSPACE_STORAGE_LOCATION")
WORKSPACE_STORAGE_BACKEND = {
    "engine": "hexa.files.backends.fs.FileSystemStorage",
    "options": {
        "data_dir": "/data",
        "ext_bind_path": WORKSPACE_STORAGE_LOCATION,
        "file_permissions_mode": 0o777,
        "directory_permissions_mode": 0o777,
    },
}

WORKSPACE_BUCKET_REGION = os.environ.get("WORKSPACE_BUCKET_REGION", "europe-west1")
WORKSPACE_BUCKET_PREFIX = os.environ.get("WORKSPACE_BUCKET_PREFIX", "")
WORKSPACE_BUCKET_VERSIONING_ENABLED = False

### AWS S3 Settings if using AWS S3 as a storage backend ###
WORKSPACE_STORAGE_BACKEND_AWS_ENDPOINT_URL = os.environ.get(
    "WORKSPACE_STORAGE_BACKEND_AWS_ENDPOINT_URL"
)
# This is the endpoint URL used when generating presigned URLs called by the client since the client
# does not have access to storage engine in local mode (http://minio:9000)
WORKSPACE_STORAGE_BACKEND_AWS_PUBLIC_ENDPOINT_URL = os.environ.get(
    "WORKSPACE_STORAGE_BACKEND_AWS_PUBLIC_ENDPOINT_URL"
)
WORKSPACE_STORAGE_BACKEND_AWS_ACCESS_KEY_ID = os.environ.get(
    "WORKSPACE_STORAGE_BACKEND_AWS_ACCESS_KEY_ID"
)
WORKSPACE_STORAGE_BACKEND_AWS_SECRET_ACCESS_KEY = os.environ.get(
    "WORKSPACE_STORAGE_BACKEND_AWS_SECRET_ACCESS_KEY"
)
WORKSPACE_STORAGE_BACKEND_AWS_BUCKET_REGION = os.environ.get(
    "WORKSPACE_STORAGE_BACKEND_AWS_BUCKET_REGION"
)

# S3 settings (Used by OpenHEXA Legacy)
AWS_USERNAME = os.environ.get("AWS_USERNAME", "")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_ENDPOINT_URL = os.environ.get("AWS_ENDPOINT_URL", "")
AWS_DEFAULT_REGION = os.environ.get("AWS_DEFAULT_REGION", "")
AWS_USER_ARN = os.environ.get("AWS_USER_ARN", "")
AWS_APP_ROLE_ARN = os.environ.get("AWS_APP_ROLE_ARN", "")
AWS_PERMISSIONS_BOUNDARY_POLICY_ARN = os.environ.get(
    "AWS_PERMISSIONS_BOUNDARY_POLICY_ARN", ""
)

# MIXPANEL
MIXPANEL_TOKEN = os.environ.get("MIXPANEL_TOKEN")
