# Generated by Django 5.1.5 on 2025-03-03 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0001_initial"),
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webapp",
            options={"verbose_name": "Webapp"},
        ),
        migrations.AddConstraint(
            model_name="webapp",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_webapp_name_per_workspace",
            ),
        ),
    ]
