# Generated by Django 5.1.5 on 2025-12-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0003_remove_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("iframe", "iFrame"),
                    ("html", "HTML"),
                    ("bundle", "Bundle"),
                    ("superset", "Superset"),
                ],
                default="iframe",
            ),
        ),
    ]
