# Generated by Django 5.2.7 on 2025-11-25 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0004_webapp_slug"),
        ("workspaces", "0052_workspace_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="webapp",
            name="unique_webapp_slug_per_workspace",
        ),
        migrations.AddConstraint(
            model_name="webapp",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("slug"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_webapp_slug_per_workspace",
            ),
        ),
    ]
