# Generated by Django 5.2.7 on 2025-12-02 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0004_webapp_type"),
        ("webapps", "0005_fix_slug_constraint"),
    ]

    operations = []
