# Generated by Django 5.2.7 on 2025-12-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0006_merge_0004_webapp_type_0005_fix_slug_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
