# Generated by Django 5.2.9 on 2026-01-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0006_merge_0004_webapp_type_0005_fix_slug_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Text content for the webapp (e.g., HTML markup, configuration, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="webapp",
            name="bundle_manifest",
            field=models.JSONField(
                blank=True,
                help_text="Manifest of files in bundle stored in bucket (JSON array of {path, size})",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webapp",
            name="bundle_uploaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when bundle was last uploaded to bucket",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webapp",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
