# Generated by Django 5.2.7 on 2025-12-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0006_merge_0004_webapp_type_0005_fix_slug_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="bundle",
            field=models.BinaryField(
                blank=True,
                help_text="Zipfile containing the webapp bundle (HTML, JS, CSS, assets)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webapp",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Text content for the webapp (e.g., HTML markup, configuration, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="webapp",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
