# Generated by Django 5.2.7 on 2025-12-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0007_webapp_bundle_webapp_content_alter_webapp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
