# Generated by Django 5.2.7 on 2026-02-13 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superset", "0003_supersetinstance_organization"),
        ("webapps", "0007_webapp_inheritance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supersetwebapp",
            name="superset_dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webapps",
                to="superset.supersetdashboard",
            ),
        ),
    ]
