# Generated by Django 5.2.11 on 2026-03-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0008_webapp_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitWebapp",
            fields=[
                (
                    "webapp_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webapps.webapp",
                    ),
                ),
                ("repository", models.CharField(max_length=255)),
                (
                    "published_commit",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("webapps.webapp", models.Model),
        ),
        migrations.AlterField(
            model_name="webapp",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
