# Generated by Django 5.2.7 on 2026-02-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superset", "0004_alter_supersetdashboard_unique_together"),
        ("webapps", "0008_alter_supersetwebapp_superset_dashboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supersetwebapp",
            name="superset_dashboard",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webapp",
                to="superset.supersetdashboard",
            ),
        ),
    ]
