# Generated by Django 5.2.12 on 2026-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0010_merge_html_bundle_to_static"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gitwebapp",
            index=models.Index(
                fields=["published_commit"], name="idx_gitwebapp_published_commit"
            ),
        ),
    ]
