# Generated by Django 5.2.12 on 2026-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0011_gitwebapp_idx_gitwebapp_published_commit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitwebapp",
            name="repository",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
