# Generated by Django 5.2.12 on 2026-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0012_alter_gitwebapp_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="show_powered_by",
            field=models.BooleanField(default=True),
        ),
    ]
