# Generated by Django 5.2.12 on 2026-03-24 20:00

from django.db import migrations, models

import hexa.webapps.validators


def initialize_subdomains(apps, schema_editor):
    Webapp = apps.get_model("webapps", "Webapp")

    for webapp in Webapp.objects.filter(subdomain__isnull=True):
        slug = webapp.slug
        if Webapp.objects.filter(subdomain=slug).exists():
            webapp.subdomain = f"{webapp.workspace.slug}-{slug}"
        else:
            webapp.subdomain = slug
        webapp.save(update_fields=["subdomain"])


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0013_add_show_powered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="subdomain",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                unique=True,
                validators=[hexa.webapps.validators.validate_subdomain],
            ),
        ),
        migrations.RunPython(initialize_subdomains, migrations.RunPython.noop),
    ]
