# Generated by Django 5.2.12 on 2026-03-24 20:00

from django.db import migrations, models

import hexa.webapps.validators
from hexa.webapps.models import create_webapp_subdomain


def initialize_subdomains(apps, schema_editor):
    from hexa.webapps.models import Webapp

    for webapp in Webapp.objects.filter(subdomain__isnull=True):
        webapp.subdomain = create_webapp_subdomain(webapp.slug, webapp.workspace)
        webapp.save(update_fields=["subdomain"])


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0013_add_show_powered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="subdomain",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                unique=True,
                validators=[hexa.webapps.validators.validate_subdomain],
            ),
        ),
        migrations.RunPython(initialize_subdomains, migrations.RunPython.noop),
    ]
