# Generated by Django 5.2.12 on 2026-04-06 15:32

from django.db import migrations, models

import hexa.webapps.validators


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0014_add_subdomain_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webapp",
            name="subdomain",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[hexa.webapps.validators.validate_subdomain],
            ),
        ),
    ]
