# Generated by Django 5.2.12 on 2026-04-06 15:32

import secrets

from django.db import migrations, models

import hexa.webapps.validators


def backfill_null_subdomains(apps, schema_editor):
    Webapp = apps.get_model("webapps", "Webapp")

    for webapp in Webapp.objects.filter(subdomain__isnull=True):
        candidate = webapp.slug
        if Webapp.objects.filter(subdomain=candidate).exists():
            candidate = f"{webapp.workspace.slug}-{webapp.slug}"
        while Webapp.objects.filter(subdomain=candidate).exists():
            candidate = f"{webapp.workspace.slug}-{webapp.slug}-{secrets.token_hex(3)}"
        webapp.subdomain = candidate
        webapp.save(update_fields=["subdomain"])


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0014_add_subdomain_field"),
    ]

    operations = [
        migrations.RunPython(backfill_null_subdomains, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="webapp",
            name="subdomain",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[hexa.webapps.validators.validate_subdomain],
            ),
        ),
    ]
