# Generated by Django 5.2.13 on 2026-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0014_webapp_custom_domain"),
        ("webapps", "0015_make_subdomain_required"),
    ]

    operations = []
