# Generated by Django 5.2.13 on 2026-04-21 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0016_merge_20260413_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webapp",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                max_length=253,
                null=True,
                unique=True,
                validators=[django.core.validators.DomainNameValidator()],
            ),
        ),
    ]
