# Generated by Django 5.2.12 on 2026-04-22 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapps", "0016_webapp_allowed_operations"),
        ("webapps", "0017_alter_webapp_custom_domain"),
    ]

    operations = []
