# Generated by Django 5.2.13 on 2026-05-27 12:44

from django.db import migrations

import hexa.user_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0040_organization_slug"),
        ("webapps", "0018_merge_20260422_1200"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebappUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "user_management.user",
                hexa.user_management.models.ServicePrincipal,
            ),
            managers=[
                ("objects", hexa.user_management.models.UserManager()),
            ],
        ),
    ]
