# Generated by Django 3.2 on 2021-04-26 12:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogIndex",
            fields=[
                (
                    "index_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.index",
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[("DATASOURCE", "Datasource"), ("CONTENT ", "Content")],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Index",
                "verbose_name_plural": "Catalog indexes",
            },
            bases=("core.index",),
        ),
        migrations.CreateModel(
            name="CatalogIndexPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalogindex",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
