# Generated by Django 3.2.3 on 2021-05-27 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_abstract_index"),
        ("catalog", "0004_abstract_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CatalogIndex",
        ),
        migrations.DeleteModel(
            name="CatalogIndexPermission",
        ),
    ]
