# Generated by Django 3.2.6 on 2021-09-01 12:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_alter_index_search"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={},
        ),
        migrations.AddIndex(
            model_name="index",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"],
                name="catalog_index_search_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="index",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["search"],
                name="catalog_index_search_gist_idx",
                opclasses=["gist_trgm_ops"],
            ),
        ),
    ]
