# Generated by Django 3.2.6 on 2021-09-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_add_gin_gist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={
                "ordering": ("external_name",),
                "verbose_name": "Index",
                "verbose_name_plural": "Indexes",
            },
        ),
    ]
