# Generated by Django 3.2.6 on 2021-09-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("catalog", "0017_postgres_base_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpermission",
            name="permission_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="indexpermission",
            name="permission_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
