# Generated by Django 4.0.4 on 2022-09-07 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_indexes_django_4"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DatasourcesSyncJob",
            new_name="DatasourcesWorkJob",
        ),
        migrations.AlterModelTable(
            name="datasourcesworkjob",
            table="catalog_datasourcesworkjob",
        ),
    ]
