# Generated by Django 4.0 on 2022-01-10 15:43

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_forced_feature_flags"),
        ("core", "0008_ci_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
