# Generated by Django 4.0.3 on 2022-04-06 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0008_teams_memberships_etc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="feature",
            table="identity.feature",
        ),
        migrations.AlterModelTable(
            name="featureflag",
            table="identity.featureflag",
        ),
        migrations.AlterModelTable(
            name="membership",
            table="identity.membership",
        ),
        migrations.AlterModelTable(
            name="organization",
            table="identity.organization",
        ),
        migrations.AlterModelTable(
            name="team",
            table="identity.team",
        ),
        migrations.AlterModelTable(
            name="user",
            table="identity.user",
        ),
    ]
