# Generated by Django 5.2.1 on 2025-06-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_management",
            "0022_organizationmembership_organization_members_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
