# Generated by Django 5.2.1 on 2025-06-26 08:57

from django.db import migrations


def remove_feature_flag(apps, schema_editor):
    Feature = apps.get_model("user_management", "Feature")
    feature = Feature.objects.filter(code="users.search")
    assert feature.count() <= 1
    feature.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0023_alter_organization_name_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_feature_flag),
    ]
