# Generated by Django 5.2.1 on 2025-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0026_organizationinvitation_workspace_invitations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinvitation",
            name="workspace_invitations",
            field=models.JSONField(
                default=list,
                help_text="List of workspace invitations with workspace_slug, workspace_name, and role",
            ),
        ),
    ]
