# Generated by Django 5.2.1 on 2025-08-14 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0027_alter_organizationinvitation_workspace_invitations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationinvitation",
            name="workspace_invitations",
        ),
    ]
