# Generated by Django 5.2.1 on 2025-08-18 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0028_migrate_users_to_bluesquare_organization"),
        ("user_management", "0028_remove_organizationinvitation_workspace_invitations"),
    ]

    operations = []
