# Generated by Django 5.2.1 on 2025-10-20 00:00

from django.db import migrations


def remove_feature_flag(apps, schema_editor):
    Feature = apps.get_model("user_management", "Feature")
    feature = Feature.objects.filter(code="organization")
    assert feature.count() <= 1
    feature.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0029_merge_20250818_0957"),
    ]

    operations = [
        migrations.RunPython(remove_feature_flag),
    ]
