# Generated by Django 5.2.7 on 2025-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0029_merge_20250818_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="icon",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.TextField(blank=True),
        ),
    ]
