# Generated by Django 5.2.7 on 2025-10-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0030_remove_organization_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="restored_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
