# Generated by Django 5.2.7 on 2026-01-12 10:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0031_organization_deleted_at_organization_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription_id", models.UUIDField(unique=True)),
                ("plan_code", models.CharField(max_length=100)),
                ("subscription_start_date", models.DateField()),
                ("subscription_end_date", models.DateField()),
                ("users_limit", models.PositiveIntegerField()),
                ("workspaces_limit", models.PositiveIntegerField()),
                ("pipeline_runs_limit", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="user_management.organization",
                    ),
                ),
            ],
            options={
                "db_table": "identity_organization_subscription",
                "ordering": ["-subscription_start_date"],
            },
        ),
    ]
