# Generated by Django 5.2.7 on 2026-01-13 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0032_add_organization_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": [
                    (
                        "manage_all_organizations",
                        "Can manage all organizations (create, update subscriptions)",
                    )
                ]
            },
        ),
    ]
