# Generated by Django 5.2.7 on 2026-01-21 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0032_signuprequest"),
        ("user_management", "0033_alter_organization_options"),
    ]

    operations = []
