# Generated by Django 5.2.9 on 2026-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0034_merge_20260121_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="assistant_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="assistant_model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
