# Generated by Django 5.2.7 on 2026-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0034_merge_20260121_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
