# Generated by Django 5.2.7 on 2026-02-04 16:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hexa.user_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0035_remove_short_name_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("access_token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                "db_table": "identity_service_account",
            },
            bases=("user_management.user",),
            managers=[
                ("objects", hexa.user_management.models.UserManager()),
            ],
        ),
    ]
