# Generated by Django 5.2.7 on 2026-02-16 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0037_serviceaccount_secure_token"),
        ("user_management", "0037_subscription_resource_limits"),
    ]

    operations = []
