# Generated by Django 5.2.9 on 2026-03-04 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hexa.core.models.cryptography


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0038_merge_20260216_0937"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("anthropic", "Anthropic")], max_length=20, null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("claude-haiku-4-5-20251001", "Claude Haiku 4.5"),
                            ("claude-opus-4-6", "Claude Opus 4.6"),
                            ("claude-sonnet-4-6", "Claude Sonnet 4.6"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "api_key",
                    hexa.core.models.cryptography.EncryptedTextField(
                        max_length=255, null=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("enabled", False),
                            models.Q(
                                ("provider__isnull", False),
                                ("model__isnull", False),
                                ("api_key__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ai_settings_enabled_requires_full_config",
                    )
                ],
            },
        ),
    ]
