# Generated by Django 5.2.9 on 2026-03-03 13:57

import django.db.models.deletion
import hexa.core.models.cryptography
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0038_merge_20260216_0937"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("anthropic", "Anthropic")], max_length=20, null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("HAIKU", "Haiku"),
                            ("OPUS", "Opus"),
                            ("SONNET", "Sonnet"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "api_key",
                    hexa.core.models.cryptography.EncryptedTextField(
                        max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
