# Generated by Django 5.2.1 on 2026-06-25 00:00

from django.db import migrations


def remove_feature_flag(apps, schema_editor):
    Feature = apps.get_model("user_management", "Feature")
    feature = Feature.objects.filter(code="assistant")
    assert feature.count() <= 1
    feature.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0043_subscription_monthly_ai_budget"),
    ]

    operations = [
        migrations.RunPython(remove_feature_flag, migrations.RunPython.noop),
    ]
