# Generated by Django 5.2.16 on 2026-10-05 12:41

from django.db import migrations, models

# Organizations that keep iframe web apps on the /play page, see
# https://github.com/BLSQ/openhexa-app/pull/1782.
PLAY_PAGE_ORGANIZATIONS = ["Sonder Collective"]


def enable_play_page(apps, schema_editor):
    Organization = apps.get_model("user_management", "Organization")
    Organization.objects.filter(name__in=PLAY_PAGE_ORGANIZATIONS).update(
        iframe_webapps_use_play_page=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0044_remove_assistant_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="iframe_webapps_use_play_page",
            field=models.BooleanField(
                default=False,
                help_text="Publish iframe web apps on the frontend /play page instead of their own subdomain (see https://github.com/BLSQ/openhexa-app/pull/1782).",
            ),
        ),
        migrations.RunPython(enable_play_page, migrations.RunPython.noop),
    ]
