# Generated by Django 5.2.9 on 2026-01-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toolexecution",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="toolexecution",
            name="executed_at",
        ),
    ]
