# Generated by Django 5.2.12 on 2026-03-18 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0001_initial"),
        ("workspaces", "0057_fix_readonly_role_grants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user"],
                name="asst_conv_user_cost_idx",
            ),
        ),
    ]
