# Generated by Django 5.2.9 on 2026-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_alter_toolexecution_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="model",
            field=models.CharField(default="", max_length=100),
        ),
    ]
