# Generated by Django 5.2.13 on 2026-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_conversation_generic_linked_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinvocation",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
