# Generated by Django 5.2.9 on 2026-01-28 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_conversation_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingToolApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_use_id", models.CharField(max_length=100)),
                ("tool_name", models.CharField(max_length=100)),
                ("tool_input", models.JSONField()),
                ("claude_response", models.JSONField()),
                ("messages_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_tokens_so_far", models.IntegerField(default=0)),
                ("output_tokens_so_far", models.IntegerField(default=0)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_approvals",
                        to="assistant.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
