# Generated by Django 5.2.12 on 2026-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_conversation_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="instruction_set",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pipeline", "Pipeline"),
                    ("edit_pipeline", "Edit Pipeline"),
                    ("webapps", "Web Apps"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
