# Generated by Django 5.2.13 on 2026-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_conversation_generic_linked_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinvocation",
            name="proposal_pending",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True while the proposal is awaiting user action; False once accepted or dismissed. "
                    "Only meaningful for tool invocations that produce a user-facing proposal "
                    "(e.g. propose_pipeline_version)."
                ),
            ),
        ),
    ]
