# Generated by Django 3.1.7 on 2021-04-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatortype",
            options={"ordering": ("name",), "verbose_name": "DHIS2 Indicator type"},
        ),
    ]
