# Generated by Django 3.1.7 on 2021-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0005_fields_rename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="hexa_url",
        ),
        migrations.AddField(
            model_name="instance",
            name="url",
            field=models.URLField(default="https://www.some.url"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instance",
            name="hexa_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
