# Generated by Django 3.2.3 on 2021-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0006_sync_fine_tuning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataelement",
            name="dhis2_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="dataelement",
            name="dhis2_short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="dataelement",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dataelement",
            name="short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="dhis2_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="dhis2_short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="indicatortype",
            name="dhis2_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="indicatortype",
            name="dhis2_short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="indicatortype",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="indicatortype",
            name="short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="short_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
