# Generated by Django 3.2.6 on 2021-08-31 08:55

from django.db import migrations, models

import hexa.plugins.connector_dhis2.models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0014_metadata_rf_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="api_url",
            field=models.URLField(
                validators=[hexa.plugins.connector_dhis2.models.validate_dhis2_base_url]
            ),
        ),
    ]
