# Generated by Django 3.2.7 on 2021-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0018_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.TextField(blank=True),
        ),
    ]
