# Generated by Django 4.0.2 on 2022-03-08 13:33

from django.db import migrations, models
from django.utils.text import slugify


def forwards_func(apps, schema_editor):

    Instance = apps.get_model("connector_dhis2", "Instance")
    db_alias = schema_editor.connection.alias
    for instance in Instance.objects.all():
        instance.slug = slugify(instance.name)
        instance.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0023_instance_verbose_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instancepermission",
            name="show_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Should the user have access to the API credentials?",
            ),
        ),
    ]
