# Generated by Django 4.0.2 on 2022-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0023_instance_verbose_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="instancepermission",
            name="enable_notebooks_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Should the user have access to the API credentials?",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
