# Generated by Django 4.0.2 on 2022-03-08 13:33

from django.db import migrations
from django.utils.text import slugify


def forwards_func(apps, schema_editor):

    Instance = apps.get_model("connector_dhis2", "Instance")
    db_alias = schema_editor.connection.alias
    for instance in Instance.objects.all():
        instance.slug = slugify(instance.name)
        instance.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0024_instance_slug_instancepermission_show_credentials"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
