# Generated by Django 4.0.2 on 2022-03-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0024_instance_slug_and_permission_notebooks_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
