# Generated by Django 4.0.2 on 2022-03-15 15:19

from django.db import migrations, models
from slugify import slugify


def forwards_func(apps, schema_editor):
    Instance = apps.get_model("connector_dhis2", "Instance")
    for instance in Instance.objects.all():
        instance.slug = slugify(instance.name, stopwords=["dhis2", "instance"])
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0025_instance_slug_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
