# Generated by Django 4.0.2 on 2022-03-21 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0025_dhis2_instance_slug_unique"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Extract",
        ),
    ]
