# Generated by Django 4.0.2 on 2022-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0025_instance_slug_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="slug",
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
