# Generated by Django 4.0.6 on 2022-07-26 08:16

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0001_data_collections"),
        ("connector_dhis2", "0029_data_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataelement",
            name="collections",
            field=models.ManyToManyField(
                related_name="+",
                through="connector_dhis2.DataElementCollection",
                to="data_collections.collection",
            ),
        ),
        migrations.AddField(
            model_name="dataelementcollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_collections.collection",
            ),
        ),
        migrations.AddField(
            model_name="dataelementcollection",
            name="data_element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="connector_dhis2.dataelement",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataelementcollection",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("data_element"),
                django.db.models.expressions.F("collection"),
                name="de_collection_unique_de_collection",
            ),
        ),
    ]
