# Generated by Django 4.0.6 on 2022-07-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector_dhis2", "0029_collections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataelementcollectionitem",
            old_name="data_element",
            new_name="item",
        ),
    ]
