# Generated by Django 4.2.16 on 2024-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_dhis2", "0031_instance_start_synced_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataelement",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="data_elements",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="indicator_type",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="indicatortype",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="api_credentials",
        ),
        migrations.RemoveField(
            model_name="instancepermission",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="instancepermission",
            name="team",
        ),
        migrations.RemoveField(
            model_name="instancepermission",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organisationunit",
            name="datasets",
        ),
        migrations.RemoveField(
            model_name="organisationunit",
            name="instance",
        ),
        migrations.DeleteModel(
            name="Credentials",
        ),
        migrations.DeleteModel(
            name="DataElement",
        ),
        migrations.DeleteModel(
            name="DataSet",
        ),
        migrations.DeleteModel(
            name="Indicator",
        ),
        migrations.DeleteModel(
            name="IndicatorType",
        ),
        migrations.DeleteModel(
            name="Instance",
        ),
        migrations.DeleteModel(
            name="InstancePermission",
        ),
        migrations.DeleteModel(
            name="OrganisationUnit",
        ),
    ]
