# Generated by Django 5.0.3 on 2024-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="allows",
            field=models.TextField(null=True),
        ),
    ]
