# Generated by Django 3.2.3 on 2021-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="oidc_target_audience",
            field=models.CharField(
                help_text='Corresponds to the <a href="https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#get_the_client_id_of_the_iam_proxy" target="_blank">client_id of the IAM Proxy</a>',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="credentials",
            name="service_account_key_data",
            field=models.JSONField(help_text="The content of the JSON key in GCP"),
        ),
    ]
