# Generated by Django 3.2.6 on 2021-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0008_auto_20210916_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagconfig",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
