# Generated by Django 3.2.7 on 2021-10-11 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0011_alter_dagrun_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dagconfig",
            options={"ordering": ["name"], "verbose_name": "DAG config"},
        ),
        migrations.AlterModelOptions(
            name="dagrun",
            options={"ordering": ("-execution_date", "-execution_date")},
        ),
        migrations.RemoveField(
            model_name="dagrun",
            name="message",
        ),
    ]
