# Generated by Django 3.2.7 on 2021-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0013_dag_run_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="dag",
            name="sample_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="dagrun",
            name="dag_config",
        ),
        migrations.AddField(
            model_name="dagrun",
            name="used_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DAGConfig",
        ),
    ]
