# Generated by Django 4.0 on 2022-01-12 21:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0007_ci_email"),
        ("connector_airflow", "0021_add_dag_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAGPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_management.user",
            ),
        ),
        migrations.DeleteModel(
            name="ClusterPermission",
        ),
        migrations.AddField(
            model_name="dagpermission",
            name="dag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connector_airflow.dag"
            ),
        ),
        migrations.AddField(
            model_name="dagpermission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_management.team"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dagpermission",
            unique_together={("dag", "team")},
        ),
    ]
