# Generated by Django 4.0.2 on 2022-03-15 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_airflow", "0027_dag_run_favorite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dagrunfavorite",
            unique_together={("user", "dag_run")},
        ),
    ]
