# Generated by Django 4.0.2 on 2022-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0028_dagrun_favorite_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dagauthorizeddatasource",
            old_name="label",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="dagauthorizeddatasource",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="A slug to identify the datasource in the pipeline. If left empty, the datasource will be available with the same name as in the notebooks",
                max_length=200,
                null=True,
            ),
        ),
    ]
