# Generated by Django 4.0.4 on 2022-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_airflow", "0032_permissions_next"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagrun",
            name="current_progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dagrun",
            name="messages",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="dagrun",
            name="outputs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="dagrun",
            name="run_logs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
