# Generated by Django 5.0.2 on 2024-04-04 10:27

import uuid

import django.contrib.postgres.functions
from django.db import migrations, models

import hexa.core.models.behaviors


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentsSyncJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "execute_at",
                    models.DateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs with higher priority will be processed first.",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("args", models.JSONField()),
            ],
            options={
                "db_table": "catalog_environmentssyncjob",
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "restored_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("code", models.CharField(default="", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("schedule", models.CharField(blank=True, max_length=200, null=True)),
                ("webhook_enabled", models.BooleanField(default=False)),
                ("cpu_request", models.CharField(blank=True, max_length=32)),
                ("cpu_limit", models.CharField(blank=True, max_length=32)),
                ("memory_request", models.CharField(blank=True, max_length=32)),
                ("memory_limit", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "Pipeline",
            },
        ),
        migrations.CreateModel(
            name="PipelineRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.CharField(max_length=200)),
                ("execution_date", models.DateTimeField()),
                ("last_heartbeat", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("queued", "Queued"),
                            ("terminating", "terminating"),
                            ("stopped", "Stopped"),
                        ],
                        max_length=200,
                    ),
                ),
                ("duration", models.DurationField(null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("access_token", models.CharField(blank=True, max_length=200)),
                ("messages", models.JSONField(blank=True, default=list, null=True)),
                ("outputs", models.JSONField(blank=True, default=list, null=True)),
                ("run_logs", models.TextField(blank=True, null=True)),
                ("current_progress", models.PositiveSmallIntegerField(default=0)),
                ("send_mail_notifications", models.BooleanField(default=False)),
                ("timeout", models.IntegerField(null=True)),
            ],
            options={
                "ordering": ("-execution_date",),
            },
            bases=(models.Model, hexa.core.models.behaviors.WithStatus),
        ),
        migrations.CreateModel(
            name="PipelineVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.SmallIntegerField()),
                ("zipfile", models.BinaryField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "timeout",
                    models.IntegerField(
                        help_text="Time (in seconds) after which the pipeline execution will be stopped (with a default value of 4 hours up to 12 max).",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
            },
        ),
    ]
