# Generated by Django 3.2 on 2021-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0001_indexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineindex",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("PIPELINES_ENVIRONMENT", "Pipeline environment"),
                    ("PIPELINES_PIPELINE", "Pipeline"),
                ],
                max_length=100,
            ),
        ),
    ]
