# Generated by Django 5.0.2 on 2024-04-04 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pipelines", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerecipient",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pipelines.pipeline"
            ),
        ),
        migrations.AddField(
            model_name="pipelinerecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="recipients",
            field=models.ManyToManyField(
                through="pipelines.PipelineRecipient", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pipelines.pipeline"
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="stopped_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="pipelines.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="pipeline_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pipelines.pipelineversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerecipient",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("pipeline"),
                name="unique_recipient_per_pipeline",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("code"),
                models.F("deleted_at"),
                name="unique_pipeline_code_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelineversion",
            constraint=models.UniqueConstraint(
                models.F("id"), models.F("number"), name="pipeline_unique_version"
            ),
        ),
    ]
