# Generated by Django 4.0 on 2021-12-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_metadata_rf_4"),
        ("pipelines", "0007_environmentssyncjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="+", to="tags.Tag"),
        ),
    ]
