# Generated by Django 4.1.3 on 2023-01-04 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0011_pipelineversion_pipelinerun_pipeline_version_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pipelinerun",
            old_name="webhook_token",
            new_name="access_token",
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="last_heartbeat",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
