# Generated by Django 4.0.4 on 2023-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0012_rename_webhook_token_pipelinerun_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="trigger_mode",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("manual", "Manual")],
                default="manual",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
