# Generated by Django 4.1.3 on 2023-03-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0017_alter_workspace_db_name_alter_workspace_db_password"),
        ("pipelines", "0013_pipelinerun_trigger_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="user",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="entrypoint",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
