# Generated by Django 4.1.3 on 2023-03-06 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0015_migrate_parameters_and_entrypoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="entrypoint",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="parameters",
        ),
    ]
