# Generated by Django 4.1.7 on 2023-04-18 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipelines",
            "0022_remove_pipeline_unique_pipeline_name_per_workspace_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelineversion",
            name="entrypoint",
        ),
    ]
