# Generated by Django 4.1.7 on 2023-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0024_pipelines_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="cpu_limit",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="cpu_request",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="memory_limit",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="memory_request",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
