# Generated by Django 4.1.7 on 2023-06-23 09:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipelines", "0025_pipeline_container_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="send_mail_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PipelineRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipelines.pipeline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="pipeline",
            name="recipients",
            field=models.ManyToManyField(
                through="pipelines.PipelineRecipient", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerecipient",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("pipeline"),
                name="unique_recipient_per_pipeline",
            ),
        ),
    ]
