# Generated by Django 4.1.7 on 2023-07-19 13:29

from django.db import migrations


def remove_scheduled_pipeline_with_paramaters(apps, schema_editor):
    Pipeline = apps.get_model("pipelines", "Pipeline")
    pipelines = Pipeline.objects.filter(
        schedule__isnull=False,
    )
    for pipeline in pipelines:
        if pipeline.versions.first().parameters:
            pipeline.schedule = None
    Pipeline.objects.bulk_update(pipelines, ["schedule"])


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0026_pipelinerun_send_mail_notifications_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_scheduled_pipeline_with_paramaters),
    ]
