# Generated by Django 4.1.7 on 2023-06-20 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipelines", "0027_pipelinerunrecipients_pipeline_recipients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PipelineRunRecipient",
            new_name="PipelineRecipient",
        ),
    ]
