# Generated by Django 4.1.7 on 2023-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0031_pipelinerun_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="webhook_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
