# Generated by Django 5.0.2 on 2024-02-27 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0033_alter_pipelinerun_trigger_mode"),
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipeline",
            name="unique_pipeline_code_per_workspace",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="restored_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("code"),
                models.F("deleted_at"),
                name="unique_pipeline_code_per_workspace",
            ),
        ),
    ]
