# Generated by Django 5.0 on 2024-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipelines",
            "0034_remove_pipeline_unique_pipeline_code_per_workspace_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pipelineversion",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="pipelineversion",
            name="pipeline_unique_version",
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipelineversion",
            name="name",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
