# Generated by Django 5.0.2 on 2024-03-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipelines",
            "0034_remove_pipeline_unique_pipeline_code_per_workspace_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="stopped_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="state",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("queued", "Queued"),
                    ("terminating", "terminating"),
                    ("stopped", "Stopped"),
                ],
                max_length=200,
            ),
        ),
    ]
