# Generated by Django 5.0.2 on 2024-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0035_pipelinerun_stopped_by_alter_pipelinerun_state"),
        ("pipelines", "0037_remove_pipelineversion_number"),
    ]

    operations = []
