# Generated by Django 5.0.3 on 2024-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0038_merge_20240405_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="notebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="type",
            field=models.CharField(
                choices=[("notebook", "Notebook"), ("default", "Default")],
                default="default",
                max_length=200,
            ),
        ),
    ]
