# Generated by Django 5.0.3 on 2024-04-17 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0039_pipeline_notebook_pipeline_type"),
        (
            "workspaces",
            "0044_remove_workspaceinvitation_workspace_invitation_unique_workspace_email",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipeline",
            name="unique_pipeline_code_per_workspace",
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("code"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_pipeline_code_per_workspace",
            ),
        ),
    ]
