# Generated by Django 5.0.3 on 2024-04-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipelines",
            "0039_remove_pipeline_unique_pipeline_code_per_workspace_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="notebook_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="type",
            field=models.CharField(
                choices=[("notebook", "Notebook"), ("zipFile", "ZipFile")],
                default="zipFile",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="pipelineversion",
            name="zipfile",
            field=models.BinaryField(null=True),
        ),
    ]
