# Generated by Django 5.0.3 on 2024-05-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0040_pipeline_notebook_path_pipeline_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="pipeline_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pipelines.pipelineversion",
            ),
        ),
    ]
