# Generated by Django 5.0.3 on 2024-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pipelines",
            "0040_remove_pipeline_unique_pipeline_code_per_workspace_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="notebook",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="notebookPath",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="type",
            field=models.CharField(
                choices=[("notebook", "Notebook"), ("zipFile", "ZipFile")],
                default="zipFile",
                max_length=200,
            ),
        ),
    ]
