# Generated by Django 5.0.3 on 2024-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0041_alter_pipelinerun_pipeline_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineversion",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
