# Generated by Django 5.0.3 on 2024-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0041_alter_pipelinerun_pipeline_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="webhook_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
