# Generated by Django 5.0.3 on 2024-06-04 20:59
from django.db import migrations


class Migration(migrations.Migration):
    def create_webhook_token(apps, schema_editor):
        Pipeline = apps.get_model("pipelines", "Pipeline")
        pipelines = Pipeline.objects.filter(webhook_enabled=True)
        for pipeline in pipelines:
            pipeline.webhook_token = pipeline.id

        Pipeline.objects.bulk_update(pipelines, ["webhook_token"])

    dependencies = [
        ("pipelines", "0042_pipeline_webhook_token"),
    ]

    operations = [
        migrations.RunPython(create_webhook_token, migrations.RunPython.noop),
    ]
