# Generated by Django 5.0.3 on 2024-06-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0044_merge_20240614_1400"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="stopped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
