# Generated by Django 5.0.9 on 2024-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0045_alter_pipelinerun_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='send_mail_notifications',
        ),
        migrations.AddField(
            model_name='pipelinerecipient',
            name='notification_event',
            field=models.CharField(choices=[('ALL_EVENTS', 'All events'), ('PIPELINE_FAILED', 'Pipeline failed')], default='ALL_EVENTS', max_length=200),
        ),
    ]
