# Generated by Django 4.2.16 on 2024-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0052_pipelineversion_version_number_revert_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="log_level",
            field=models.IntegerField(
                choices=[
                    (0, "DEBUG"),
                    (1, "INFO"),
                    (2, "WARNING"),
                    (3, "ERROR"),
                    (4, "CRITICAL"),
                ],
                default=1,
            ),
        ),
    ]
