# Generated by Django 4.2.17 on 2024-12-31 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_templates", "0003_alter_pipelinetemplate_options"),
        ("pipelines", "0054_pipeline_source_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineversion",
            name="source_template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_versions",
                to="pipeline_templates.pipelinetemplateversion",
            ),
        ),
    ]
