# Generated by Django 4.2.17 on 2025-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0055_pipelineversion_source_template_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["access_token"], name="pipelines_p_access__4788e4_idx"
            ),
        ),
    ]
