# Generated by Django 4.2.17 on 2025-02-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0056_pipelinerun_pipelines_p_access__4788e4_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipeline",
            name="unique_pipeline_code_per_workspace",
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                models.F("workspace_id"),
                models.F("code"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_pipeline_code_per_workspace",
                violation_error_message="A pipeline with the same code already exists in this workspace. Consider using `create_with_unique_code` method.",
            ),
        ),
    ]
