# Generated by Django 3.1.6 on 2021-02-09 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dhis2Indicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("dhis2_code", models.CharField(blank=True, max_length=100)),
                ("dhis2_name", models.CharField(max_length=200)),
                ("dhis2_short_name", models.CharField(blank=True, max_length=100)),
                ("dhis2_description", models.TextField(blank=True)),
                (
                    "dhis2_indicator_type",
                    models.CharField(
                        choices=[
                            ("NUMBER_FACTOR_1", "Number (Factor 1)"),
                            ("PER_CENT", "Per cent"),
                            ("PER_HUNDRED_THOUSANDS", "Per hundred thousand"),
                            ("PER_TEN_THOUSAND", "Per ten thousand"),
                            ("PER_THOUSAND", "Per thousand"),
                        ],
                        max_length=100,
                    ),
                ),
                ("dhis2_annualized", models.BooleanField()),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.area",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.datasource",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["dhis2_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dhis2DataElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("dhis2_code", models.CharField(blank=True, max_length=100)),
                ("dhis2_name", models.CharField(max_length=200)),
                ("dhis2_short_name", models.CharField(blank=True, max_length=100)),
                ("dhis2_description", models.TextField(blank=True)),
                (
                    "dhis2_domain_type",
                    models.CharField(
                        choices=[("AGGREGATE", "Aggregate"), ("TRACKER", "Tracker")],
                        max_length=100,
                    ),
                ),
                (
                    "dhis2_value_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("LONG_TEXT", "Long text"),
                            ("LETTER", "Letter"),
                            ("PHONE_NUMBER", "Phone number"),
                            ("EMAIL", "Email"),
                            ("YES_NO", "Yes/No"),
                            ("YES_ONLY", "Yes Only"),
                            ("DATE", "Date"),
                            ("DATE_AND_TIME", "Date & Time"),
                            ("TIME", "Time"),
                            ("NUMBER", "Number"),
                            ("UNIT_INTERVAL", "Unit interval"),
                            ("PERCENTAGE", "Percentage"),
                            ("INTEGER", "Integer"),
                            ("POSITIVE_INTEGER", "Positive Integer"),
                            ("INTEGER_POSITIVE", "Positive Integer"),
                            ("NEGATIVE_INTEGER", "Negative Integer"),
                            ("INTEGER_NEGATIVE", "Negative Integer"),
                            ("POSITIVE_OR_ZERO_INTEGER", "Positive or Zero Integer"),
                            ("INTEGER_ZERO_OR_POSITIVE", "Positive or Zero Integer"),
                            ("TRACKER_ASSOCIATE", "Tracker Associate"),
                            ("USERNAME", "Username"),
                            ("COORDINATE", "Coordinate"),
                            ("ORGANISATION_UNIT", "Organisation Unit"),
                            ("AGE", "Age"),
                            ("URL", "URL"),
                            ("FILE", "File"),
                            ("IMAGE", "Image"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "dhis2_aggregation_type",
                    models.CharField(
                        choices=[("SUM", "Sum"), ("AVERAGE", "Average")], max_length=100
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.area",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.datasource",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["dhis2_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dhis2Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_url", models.URLField()),
                ("api_username", models.CharField(max_length=200)),
                ("api_password", models.CharField(max_length=200)),
                (
                    "datasource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector",
                        to="catalog.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
