import { AssistantToolName } from "graphql/types";

// Canonical roster of assistant tool machine names. `AssistantToolName` is
// code-generated by GraphQL codegen from `assistant_tools.generated.graphql`,
// which the backend regenerates from the agent registry (the real source of
// truth — every tool any agent can call). So tool identities live in exactly one
// place (the Python agents) and flow here automatically; this module just gives
// them a stable, conventional name for the rest of the assistant UI to key off.
export const TOOL = AssistantToolName;

export type ToolName = AssistantToolName;
