# Generated by Django 3.2.7 on 2021-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={
                "ordering": ("label",),
                "verbose_name": "Dashboard index",
                "verbose_name_plural": "Dashboard indexes",
            },
        ),
    ]
