# Generated by Django 4.0.4 on 2022-04-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0009_user_management_to_identity_1"),
        ("visualizations", "0003_indexes_django_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldashboardpermission",
            name="mode",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="EDITOR",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="externaldashboardpermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="externaldashboardpermission",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
    ]
