# Generated by Django 4.0.4 on 2022-04-13 05:35

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_user_management_to_identity_1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("visualizations", "0003_indexes_django_4"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="externaldashboardpermission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="externaldashboardpermission",
            name="mode",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="EDITOR",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="externaldashboardpermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="externaldashboardpermission",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="externaldashboardpermission",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("user"),
                django.db.models.expressions.F("team"),
                django.db.models.expressions.F("external_dashboard"),
                name="dashboard_unique_user_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="externaldashboardpermission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team__isnull", False), ("user__isnull", False), _connector="OR"
                ),
                name="dashboard_permission_user_or_team_not_null",
            ),
        ),
    ]
