# Generated by Django 4.0.4 on 2022-04-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualizations", "0005_externaldashboardpermission_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldashboardpermission",
            name="mode",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="EDITOR",
                max_length=200,
            ),
        ),
    ]
