# Generated by Django 5.2.14 on 2026-07-07 08:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0060_grant_create_on_public_to_rw_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseQueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                            ("DENIED", "Denied"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=5, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(null=True)),
                ("row_count", models.PositiveIntegerField(null=True)),
                ("truncated", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        choices=[("API", "Api"), ("DATA_STUDIO", "Data Studio")],
                        default="API",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="database_query_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="databases_d_workspa_8ade73_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="databases_d_user_id_0b5e5d_idx",
                    ),
                ],
            },
        ),
    ]
