name: Build Platform image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Platform image tag
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    # see https://github.com/docker/build-push-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@044aaa9258972fc1ab44730789e42d66b720789c
      - name: Login to DockerHub
        uses: docker/login-action@adb73476b6e06caddec5db0bc1deacbec8cdd947
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@6efc2b01cbb63cfc68c370c6c806586fa6384a3a
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            blsq/habari-platform:${{ github.event.inputs.tag }}
            blsq/habari-platform:latest

