#name: Release
#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: Environment identifier
#        required: true
#        default: demo
#
#jobs:
#  release:
#    name: Release
#    environment:
#      name: ${{ github.event.inputs.environment }}
#    runs-on: ubuntu-latest
#    env:
#      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
#      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#      GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
#
#    steps:
#      # Checkout code
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform
#      # Cloud user API token
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec
#        with:
#          terraform_version: 1.0.0
#
#      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state,
#      # downloading modules, etc.
#      - name: Terraform Init
#        run: |
#          terraform -chdir=terraform init -backend-config="bucket=${{ secrets.TERRAFORM_GCS_BUCKET }}"
#
#      # Generates an execution plan for Terraform
#      - name: Terraform Plan
#        run: |
#          terraform -chdir=terraform/${{ github.event.inputs.environment }} plan -out=saved_plan
#
#      # Apply the changes required to reach the desired state of the configuration, or the pre-determined set of
#      # actions generated by terraform plan
#      - name: Terraform apply
#        run: terraform -chdir=terraform apply saved_plan
