name: Test suite
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker app image
        env:
          DOCKER_BUILDKIT: 1
        run: docker-compose build

      - name: Run Django tests
        run: docker-compose run -e DEBUG=false app coveraged-test

      - name: Run dataworker tests
        run: docker-compose run -e DEBUG=false app datasciences-test
